### ISSUE TITLE
Update documentation on how to test and deploy umbrel apps on umbrelOS 1.0

### ISSUE THREAD

**Issue by knorrium** [getumbrel/umbrel-apps#1025]
Discussed with @lukechilds over Twitter that [the current steps](https://github.com/getumbrel/umbrel-apps?tab=readme-ov-file#3-testing-the-app-on-umbrel) for packaging and testing apps no longer work for umbrelOS 1.0 due to the Docker change. 

Tracking it as an issue to be able to subscribe to updates.

Thanks!

**Comment by highghlow** [comment]
I think the documentation got updated

**Comment by mayankchhabra** [comment]
That's correct https://github.com/getumbrel/umbrel-apps/commit/f679aac0eeb9e92092e3fbb68c5c446854f170b4. Closing the issue :)
