### ISSUE TITLE
Add an app for paperless-ngx

### ISSUE THREAD

**Issue by maxime1992** [getumbrel/umbrel-apps#1035]
https://docs.paperless-ngx.com is in my top 3 of apps to self host.

Compared to some apps that have a non open source equivalent at least, I don't think I've ever used an app that comes anywhere near paperless-ngx.

It'd be fantastic if you could add support for it :pray:!

Thanks

**Comment by highghlow** [comment]
I have started working on this request

**Comment by highghlow** [comment]
It's done

**Comment by nmfretz** [comment]
Paperless-ngx is now available in the app store thanks to @highghlow! Closed by https://github.com/getumbrel/umbrel-apps/commit/3cb4c100c1a428629680d53d2e479c1e04e73d8d.
