### ISSUE TITLE
Update Plex

### ISSUE THREAD

**Issue by marciasmedia** [getumbrel/umbrel-apps#1053]
Please update server plex : my version : 1.40.0 / now new version 1.40.1

Thanks

**Comment by highghlow** [comment]
I have started working on this request

**Comment by highghlow** [comment]
Awaiting merge

**Comment by marciasmedia** [comment]
how long can you wait for a simple update??? Have mercy, people

**Comment by highghlow** [comment]
> how long can you wait for a simple update??? Have mercy, people

The developers are busy porting v1.0 to Linux. Give them time!
Luke said the devs will review my PRs this week.

**Comment by marciasmedia** [comment]
Ok I see

**Comment by nmfretz** [comment]
Thanks @marciasmedia and @highghlow. Plex has now been updated to latest 1.40.2: https://github.com/getumbrel/umbrel-apps/pull/1056
