### ISSUE TITLE
[Update Request] Audiobookshelf 2.8.0 > 2.9.0

### ISSUE THREAD

**Issue by cor-bee** [getumbrel/umbrel-apps#1065]
I would be grateful if someone could update this app to its latest version:
https://github.com/advplyr/audiobookshelf/releases/tag/v2.9.0

**Comment by cor-bee** [comment]
Opened PR #1080 to update Audiobookshelf from v2.8.0 to v2.9.0

**Comment by FlyinPancake** [comment]
Can you close the issue as the PR is now merged?
