### ISSUE TITLE
Request update to Ghostfolio

### ISSUE THREAD

**Issue by 701789262a** [getumbrel/umbrel-apps#1108]
Due to Yahoo API change, Ghostfolio fails to retrieve values and is unusable.
Version 2.82.0 should fix, can someone change it?

**Comment by mikropsoft** [comment]
Updated @701789262a

**Comment by dtslvr** [comment]
PR: https://github.com/getumbrel/umbrel-apps/pull/1115

You could close this issue @nmfretz.

**Comment by nmfretz** [comment]
Thanks @dtslvr. Closing as completed https://github.com/getumbrel/umbrel-apps/pull/1115
