### ISSUE TITLE
Request to update; Jellyfish, SABnzbd

### ISSUE THREAD

**Issue by kraken-XIV** [getumbrel/umbrel-apps#1113]
Hi there,

it’s been a while since the last app update for SABnzbd and Jellyfish for Umbrel. Wouldn’t be possible to create an updated version of both?

Not every plugin works with the current jellyfin version.

**Comment by fabricionaweb** [comment]
#1153 in progress

**Comment by nmfretz** [comment]
Updated! Thanks for the requests.

**Comment by kraken-XIV** [comment]
> Updated! Thanks for the requests.

Much appreciated ✌️
