### ISSUE TITLE
[App Request] : myspeed

### ISSUE THREAD

**Issue by mikropsoft** [getumbrel/umbrel-apps#1122]
https://github.com/gnmyt/myspeed

Librespeed is bad for me, I really prefer this application. I would really like you to remove librespeed for redundancy and add this application and the speedtest-tracker application on the previous issue I opened.

**Comment by nmfretz** [comment]
Thanks for the app request @mikropsoft. MySpeed is now live in the app store thanks to @gnmyt!

Closed by https://github.com/getumbrel/umbrel-apps/commit/fbc07f565e3f7f1f9228e4e86be0915e989d9b87
