### ISSUE TITLE
[App Request] - Plausible

### ISSUE THREAD

**Issue by wont-stream** [getumbrel/umbrel-apps#1138]
I noticed you guys had Umami, but didn’t see Plausible — Plausible is another self hosted analytics solution which has an even smaller client script than Umami.

**Comment by mikropsoft** [comment]
https://github.com/plausible/analytics

**Comment by wont-stream** [comment]
Oops, my bad forgot to link plausible, thanks @mikropsoft

**Comment by wont-stream** [comment]
bumping this

**Comment by arguser** [comment]
I was about to switch from Plausible to Umami, but the Umami app doesn't work on Umbrel Home. So I might end up making a PR for a Plausible app :)

**Comment by wont-stream** [comment]
> I was about to switch from Plausible to Umami, but the Umami app doesn't work on Umbrel Home. So I might end up making a PR for a Plausible app :)

That would be great :D

**Comment by arguser** [comment]
Soon ™️ 
![image](https://github.com/user-attachments/assets/ed866780-a38e-46eb-9a17-3e49722c75b1)

**Comment by wont-stream** [comment]
I could help test for sure

**Comment by wont-stream** [comment]
Thank you so much :D
