### ISSUE TITLE
Please update NODERED

### ISSUE THREAD

**Issue by marciasmedia** [getumbrel/umbrel-apps#1166]
Great home-assistant (my media) update at last.

Dear beloved Umbrel team !
Update the nodered app so that I have a nanow version of node.js and npm.

You can't install some important modules because they no longer support node.js version below v18. 
Currently nodered has node.js version v16.

**Comment by nmfretz** [comment]
Node-RED has now been updated to 4.0! https://github.com/getumbrel/umbrel-apps/pull/1172. Thanks again for the request @marciasmedia

**Comment by marciasmedia** [comment]
Great !!!!!!!! Thank You !!!PozdrawiamJakubWiadomość napisana przez Nathan Fretz ***@***.***> w dniu 24.06.2024, o godz. 04:55:﻿
Node-RED has now been updated to 4.0! #1172. Thanks again for the request @marciasmedia
