### ISSUE TITLE
Pleas update Cloudlfare Tunnel

### ISSUE THREAD

**Issue by marciasmedia** [getumbrel/umbrel-apps#1169]
There is a new version of the cloudfare tunnel application

**Comment by nmfretz** [comment]
Thanks for this update request @marciasmedia! The Cloudflare Tunnel app is really great.

@Radiokot, do you happen to have any nearterm plans to update Cloudflare? https://github.com/getumbrel/umbrel-apps/pull/891

**Comment by Radiokot** [comment]
Hi @nmfretz and @marciasmedia .
Should I? Indeed, there's a newer version, but it won't bring new features to the app. Have the currently used one stopped working, or declared vulnerable?

**Comment by marciasmedia** [comment]
No, there is nothing wrong with the current version. I just noticed that there is a new version, so I am informing you immediately, for the reason that for such a cool Umbrel system it is good to have up-to-date applications.

**Comment by Radiokot** [comment]
Thank you, I'll check it out once I have the ability to test it properly.

**Comment by nmfretz** [comment]
Hi all, Cloudflare was updated by @Radiokot a couple weeks ago 🤝. https://github.com/getumbrel/umbrel-apps/pull/1234

Closing as completed.
