### ISSUE TITLE
[UPDATE] immich to version 1.107.1 for mobile app support.

### ISSUE THREAD

**Issue by EphraimElgrabli** [getumbrel/umbrel-apps#1186]
Hey there! 👋
I was wondering if we could bump up Immich to version 1.107.1? The current version we're running doesn't work with the mobile app.
I noticed that 1.107.1 actually supports the mobile app, which would be super awesome! It'd be great if we could update to this version so everyone can use Immich on their phones too.
Thanks for considering it!

**Comment by joaovictor-local** [comment]
https://github.com/getumbrel/umbrel-apps/pull/1184
There is a pull just waiting for be review and merged.

**Comment by nmfretz** [comment]
Thanks for the request @EphraimElgrabli, and for testing the PR @joaovictor-local 🙏

Immich is now updated https://github.com/getumbrel/umbrel-apps/pull/1184

@EphraimElgrabli, can you let me know what mobile device you are running on? On iOS I was not having any issues with the latest Immich client (v1.107.1) and the previous Immich server on umbrel before this update (v1.106.4). Also, the release notes for Immich don't mention an incompatibility for those client/server versions.

**Comment by EphraimElgrabli** [comment]
It seems the issue was on my end. I believe it was caused by a local proxy app I have installed, which was blocking requests to Umbrel. Thank u for your time and help.
