### ISSUE TITLE
Jam App Issues - "No connection to backend: The server reported a problem: 502 Bad Gateway"

### ISSUE THREAD

**Issue by jmurphypga** [getumbrel/umbrel-apps#1202]
<img width="1363" alt="Screenshot 2024-07-12 at 2 52 04 PM" src="https://github.com/user-attachments/assets/8db89c4a-473c-47fc-9af1-df53ea440e06">

I've been trying to find the fix for this issue and nothing I seem to do gets this to work. I've deleted and reinstall tried multiple times using same issues people had when updating to Bitcoin Core 26.0. I am currently running Bitcoin Core 27.0

I'm currently using Umbrel on a Raspberry Pi 4 on umbrelOS 1.2.1

I've tried fixing it here to no luck: https://jamdocs.org/software/installation/

The`jmwalletd` and `ob-watcher` services repeatedly fail with exit code 1.

I suspect there might be compatibility issues with Bitcoin Core version 27.0 or specific configuration requirements that haven't been documented yet.

Any guidance or recommendations on how to resolve this issue would be greatly appreciated.

Jam App Troubleshoot logs: 

jam_app_proxy_1  | yarn run v1.22.19
jam_app_proxy_1  | $ node ./bin/www
jam_app_proxy_1  | [HPM] Proxy created: /  -> http://jam_web_1:80
jam_app_proxy_1  | Waiting for jam_web_1:80 to open...
jam_web_1        | [WARN  tini (6)] Tini is not running as PID 1 and isn't registered as a child subreaper.
jam_web_1        | Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
jam_web_1        | To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
jam_web_1        | Remove leftover wallet lockfiles before startup...
jam_web_1        | ~/.joinmarket/ssl /src/scripts
jam_web_1        | Generating a RSA private key
jam_web_1        | ......................................++++
jam_web_1        | ............................................................++++
jam_web_1        | writing new private key to 'key.pem'
jam_web_1        | -----
jam_web_1        | /src/scripts
jam_web_1        | Waiting for bitcoind to accept RPC requests...
jam_web_1        | Successfully waited for bitcoind to accept RPC requests.
jam_web_1        | Creating wallet jam_default if missing...
jam_web_1        | Loading wallet jam_default...
jam_web_1        | [  OK  ] nginx
jam_web_1        | [  OK  ] tor
jam_web_1        | [  OK  ] jmwalletd
jam_web_1        | [  OK  ] ob-watcher
jam_web_1        | [  OK  ] boot
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_app_proxy_1  | Jam is now ready...
jam_app_proxy_1  | Listening on port: 5002
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
tor_server-1     | Jul 12 18:39:24.458 [notice] Tor 0.4.7.8 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1n, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Glibc 2.31 as libc.
tor_server-1     | Jul 12 18:39:24.459 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
tor_server-1     | Jul 12 18:39:24.463 [notice] Read configuration file "/tmp/torrc".
tor_server-1     | Jul 12 18:39:24.492 [notice] Opening Socks listener on 127.0.0.1:9050
tor_server-1     | Jul 12 18:39:24.492 [notice] Opened Socks listener connection (ready) on 127.0.0.1:9050
tor_server-1     | Jul 12 18:39:24.000 [notice] Bootstrapped 0% (starting): Starting
tor_server-1     | Jul 12 18:39:24.000 [notice] Starting with guard context "default"
tor_server-1     | Jul 12 18:39:25.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
tor_server-1     | Jul 12 18:39:27.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
tor_server-1     | Jul 12 18:39:27.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
tor_server-1     | Jul 12 18:41:47.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
tor_server-1     | Jul 12 18:41:47.000 [notice] Bootstrapped 20% (onehop_create): Establishing an encrypted directory connection
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
tor_server-1     | Jul 12 18:41:47.000 [notice] Bootstrapped 25% (requesting_status): Asking for networkstatus consensus
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
tor_server-1     | Jul 12 18:41:47.000 [notice] Bootstrapped 30% (loading_status): Loading networkstatus consensus
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
tor_server-1     | Jul 12 18:41:48.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
tor_server-1     | Jul 12 18:41:48.000 [notice] Bootstrapped 40% (loading_keys): Loading authority key certs
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
tor_server-1     | Jul 12 18:41:48.000 [notice] The current consensus has no exit nodes. Tor can only build internal paths, such as paths to onion services.
jam_app_proxy_1  | [HPM] Upgrading to WebSocket
tor_server-1     | Jul 12 18:41:48.000 [notice] Bootstrapped 45% (requesting_descriptors): Asking for relay descriptors
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
tor_server-1     | Jul 12 18:41:48.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/7489, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)
tor_server-1     | Jul 12 18:41:48.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/7489, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)
tor_server-1     | Jul 12 18:41:49.000 [notice] Bootstrapped 50% (loading_descriptors): Loading relay descriptors
tor_server-1     | Jul 12 18:41:50.000 [notice] The current consensus contains exit nodes. Tor can build exit and internal paths.
tor_server-1     | Jul 12 18:41:53.000 [notice] Bootstrapped 55% (loading_descriptors): Loading relay descriptors
tor_server-1     | Jul 12 18:41:53.000 [notice] Bootstrapped 61% (loading_descriptors): Loading relay descriptors
tor_server-1     | Jul 12 18:41:53.000 [notice] Bootstrapped 69% (loading_descriptors): Loading relay descriptors
tor_server-1     | Jul 12 18:41:54.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
tor_server-1     | Jul 12 18:41:54.000 [notice] Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
tor_server-1     | Jul 12 18:41:54.000 [notice] Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
tor_server-1     | Jul 12 18:41:54.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
tor_server-1     | Jul 12 18:41:54.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
tor_server-1     | Jul 12 18:41:54.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
tor_server-1     | Jul 12 18:41:55.000 [notice] Bootstrapped 100% (done): Done
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd process terminated with exit code 1
jam_web_1        | dinit: Service jmwalletd restarting too quickly; stopping.
jam_web_1        | [STOPPD] jmwalletd
jam_web_1        | dinit: Service ob-watcher process terminated with exit code 1
jam_web_1        | dinit: Service ob-watcher restarting too quickly; stopping.
jam_web_1        | [STOPPD] ob-watcher

**Comment by nmfretz** [comment]
Hi @jmurphypga, I have just tried to recreate your issue with the same Jam and Core versions as you on my Raspberry Pi 4, but everything is working for me.

> I suspect there might be compatibility issues with Bitcoin Core version 27.0 or specific configuration requirements that haven't been documented yet.

The most recent Bitcoin Node version in the app store (27.0 as of my writing) has `deprecatedrpc=create_bdb` enabled via a cli-argument, which is what allows integration with JoinMarket and the Jam app by default. This was the fix that was put in place to solve the issue people were having with Core v26.0.

Can you let me know the following:

1) After upgrading the Bitcoin Node app to v27.0, have you restarted the Jam app? It sounds like you've re-installed it, which would have the same effect, but for good measure can you please restart Jam and let me know if the issue persists? To restart Jam you can right-click on the Jam app icon from your umbrelOS homescreen and click "Restart".

2) Have you made any changes to your Bitcoin Core settings, either through the Advanced Settings UI in the Bitcoin Node app, or manually to the `bitcoin.conf`? If so, can you please let me know of any configuration changes so I can try to recreate the issue on my end?

**Comment by jmurphypga** [comment]
I have restarted the Jam app (as well as downloaded/restarted/uninstalled/redownloading it) quite a few times, but I always run into the same issue. 

After upgrading from Bitcoin Core v26 to v27.0, I have not made changes to the Bitcoin core app. As for Advanced settings, I don't know what they should be to get this to work. I am not aware of any changes made through the Advanced Settings UI.

**Comment by jmurphypga** [comment]
I'm experiencing multiple SOCKS5 connection failures and some "host unreachable" errors in my Bitcoin node's `debug.log`. Here are some sanitized excerpts from my log:

```
```
2024-04-06T14:18:10Z New block-relay-only v1 peer connected ...
2024-04-06T14:19:58Z Socks5() connect to <IP_ADDRESS>:8333 failed ...
2024-04-06T14:20:00Z Socks5() connect to <IP_ADDRESS>:8333 failed ...
...
```
```

I am unsure if this is it but there might be an issue with my proxy configuration or network connectivity. Could you give me some guidance on how to fix these issues?

Thank you!

**Comment by nmfretz** [comment]
Hey @jmurphypga, thanks for the response. Those SOCKS5 connection failures are a normal occurrence. There is likely some other underlying issue. 

Can you please create a new post under the apps-support section of our Community Support Discord and tag me directly (@natefretz):
https://discord.com/channels/936694604231766046/1196548952825278564

I can help you in a live setting there to troubleshoot this efficiently and not leave you waiting!

**Comment by nmfretz** [comment]
Closing old support issue.
