### ISSUE TITLE
[Update] Libre Translate to v1.6.0

### ISSUE THREAD

**Issue by DavidGarciaCat** [getumbrel/umbrel-apps#1216]
Good day,

I have noticed the current version for Libre Translate is [1.5.7](https://github.com/getumbrel/umbrel-apps/blob/master/libretranslate/docker-compose.yml#L10C12-L10C41), but the next release ([v1.6.0](https://hub.docker.com/layers/libretranslate/libretranslate/v1.6.0/images/sha256-91c12682b02dd3f2d775dd6518433eeab86fb8856fdcf3db7006e295e32eac52?context=explore)) is already available, which seems to include additional API options to request [alternative translations](https://libretranslate.com/docs/#/translate/post_translate) (giving us more choices).

I have noticed the Docker images used include a SHA hash, but I didn't see a match for them while browsing the [libretranslate/libretranslate](https://hub.docker.com/r/libretranslate/libretranslate/tags) image at Docker Hub, so I am not sure how to test it myself. Maybe if someone can guide me, I would be able to test it myself (either for this update or upcoming versions).

In the meantime, can anyone please provide an update on this?

Thanks!

PS: I have noticed that Pi-Hole has been updated, too, but this final update is missing here. So, if someone can point me to help with how the updates can be tested and committed for PR reviews, I can try investing some time. Cheers!

**Comment by anthony-robin** [comment]
LibreTranslate have been updated to `v1.6.0` in #1263 ;)

**Comment by DavidGarciaCat** [comment]
I think I saw an update a couple of weeks ago.
Thanks for the ping, anyway!
