### ISSUE TITLE
Problems setting up jellyseer

### ISSUE THREAD

**Issue by FlyinPancake** [getumbrel/umbrel-apps#1291]
I have been having problems with setting up jellyseer using the jellyfin instance running on my umbrel. 

Can someone look into it and help me out?

I am getting 401s when I try to complete the first step of the setup even if I use the local IPs or the tailscale domain name.

**Comment by nmfretz** [comment]
Hey @FlyinPancake, are you still having issues connecting Jellyseerr to Jellyfin? If so, can you please open a help thread on our Discord and we can help you live https://discord.gg/y9bBm8ca

When connecting Jellyseerr to Jellyfin you'll want to use this format: `http://<your-local-ip>:<jellyfin-port>`, so it would look something like this: `http://192.168.4.69:8096`. We should look into autoconfiguring jellyseerr better in the future.

**Comment by FlyinPancake** [comment]
Thank you!

And yes I am still having the same issue.

**Comment by FlyinPancake** [comment]
For future ref the discussion was directed here: https://discord.com/channels/936694604231766046/1271011400562511962
