### ISSUE TITLE
Since the update BTCPay to 1.13.5 the app no ​​longer works - "BTC node synching - Name or service not known (nbxplorer:32838)"

### ISSUE THREAD

**Issue by JurGi7** [getumbrel/umbrel-apps#1292]
According to Dennis, the problem seems to be in umbrel-apps.

The problem is described here: https://github.com/btcpayserver/btcpayserver/issues/6128

**Comment by nmfretz** [comment]
Thanks for bringing this to our attention @JurGi7. And to @ElucGeek for the btcpayserver repo issue and @dennisreimann for the PR fix 🤝
