### ISSUE TITLE
mempool times out loading ₿itcoin addresses

### ISSUE THREAD

**Issue by aphex3k** [getumbrel/umbrel-apps#134]
e.g. in the umbrel default configuration the mempool app for address 357a3So9CbsNfBBgFYACGvxxS6tMaDoa1P will produce the below error.

```
Error loading address data.
([object ProgressEvent])
```

<img width="1464" alt="image" src="https://user-images.githubusercontent.com/433270/188354609-29c68d1d-fd81-4999-b318-ac3b581c768c.png">

it doesn't matter wether the app was opened via local host name or tor onion.

Occasionally the following error displays instead (for the same addresses in question)

```
Error loading address data.
(<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> )
```

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/433270/188358078-4ccc843d-77b4-41f2-b4ea-b6f6794095b3.png">

**Comment by nmfretz** [comment]
Just recreated; thanks for reporting @aphex3k.

Looks like this is a limitation of Electrs: 
<img width="790" alt="image" src="https://github.com/getumbrel/umbrel-apps/assets/85373263/6430876e-5519-4790-a632-50454e206033">

Our roadmap for umbrelOS includes the ability for apps to register for optional protocols (e.g., different Bitcoin node RPCs or different Electrum connections). So in the future if there was both an Electrs and a Fulcrum app on Umbrel then users could register their mempool app to use whichever electrum server they choose.
