### ISSUE TITLE
[Update Request] LNbits to 0.12.10

### ISSUE THREAD

**Issue by Ghooosstt** [getumbrel/umbrel-apps#1358]
Hello,

Is it possible to update the LNbits version from 0.12.2 to 0.12.10?
https://github.com/lnbits/lnbits/releases/tag/0.12.10

Thank you

**Comment by nmfretz** [comment]
Thanks @Ghooosstt. Closing as completed by your PR https://github.com/getumbrel/umbrel-apps/pull/1370 💪
