### ISSUE TITLE
Feature Request for Umbrel os

### ISSUE THREAD

**Issue by Aditya-R-K** [getumbrel/umbrel-apps#1373]
Please add option to create a shareable volumes and let the user share that with different apps, like some time I want to share the data of nextcloud with samba app but I can't because umbrel os uses docker and they are created with different volumnes.

but we can add functionality using docker volumes. this will be useful if user want to use different apps with same files and sync, possibilities are endless

**Comment by Magnusretrotech** [comment]
This is the repo for apps. Submit Umbrel feature requests here: https://github.com/getumbrel/umbrel

**Comment by Aditya-R-K** [comment]
Okay, Thanks
