### ISSUE TITLE
When ord upgrade to 0.19, it's still running on 0.18

### ISSUE THREAD

**Issue by twosatsmaxi** [getumbrel/umbrel-apps#1374]
@nmfretz: Can I raise a pull request upgrading it to 0.19 but I think currently, yours docker image is being used?

**Comment by twosatsmaxi** [comment]
@nmfretz ^

**Comment by nmfretz** [comment]
Will get on this right away @twosatsmaxi! Sorry for the delayed response, I was away this past week.

**Comment by nmfretz** [comment]
PR: https://github.com/getumbrel/umbrel-apps/pull/1406

**Comment by nmfretz** [comment]
Update is now live! Thanks again for the ping @twosatsmaxi
