### ISSUE TITLE
Aplications request

### ISSUE THREAD

**Issue by Bammede** [getumbrel/umbrel-apps#138]
- Adguard Home
- Homarr (Server Dashboard)
- WG-Easy (Wireguard Easy)
- Twingate
- HashBackup Server Backup
- Rclone
- Apprise (Push Notifications)
- Navidrome
- Storj Self-hosted S3 Compatible Gateway

**Comment by nmfretz** [comment]
Thanks for these requests @Bammede.

Both Adguard Home and WG-Easy are now available in the Umbrel App Store! For easier tracking I have opened separate `[App Request] - <app>` Issues for your remaining suggestions

**Comment by owmsoton** [comment]
@Bammede.

work has started in [Pull request 1232](https://github.com/getumbrel/umbrel-apps/pull/1232)

**Comment by netboy69** [comment]
Can you guys add twingate to umbrel?
