### ISSUE TITLE
Home Assistant - Auto discovery not working

### ISSUE THREAD

**Issue by TheHelloDev** [getumbrel/umbrel-apps#140]
In homeassistant, a very important feature is auto discovery, this discovers smart home devices such as chromecast devices, printers, routers and more automatically. This is a great starting point for new users. Currently, when installed through the umbrel app store, auto discovery does not work.

network_mode needs to be set to host. This is seen in the [official home assistant docker image ](https://www.home-assistant.io/installation/raspberrypi#docker-compose)

**Comment by Querzel** [comment]
Looks like it's now running on network_mode: host.

**Comment by lukechilds** [comment]
Will close as resolved, @TheHelloDev feel free to re-open if this isn't working for you in the latest version.
