### ISSUE TITLE
BTCPAY server cannot connect to local bitcoin node

### ISSUE THREAD

**Issue by urcheon2022** [getumbrel/umbrel-apps#141]
On the main page of BTC PAY I'm getting the following error

> BTC
> The node is offline
> Last error: Connection refused (10.21.21.20:32838)
> 

...which in turn fails invoices:
BTC_LNURLPAY: Payment method unavailable (Full node not available)

This most likely due to this configuration in the docker.compose.yml:
BTCPAY_BTCEXPLORERURL: "http://$APP_BTCPAY_SERVER_NBXPLORER_IP:32838"

While when I look at the docker ps I can see that this NBXPLORER has no assigned/open port
```
CONTAINER ID   IMAGE                                    COMMAND                  CREATED         STATUS                   PORTS                                                                                                                                 NAMES
ad1e23dcfaa4   btcpayserver/btcpayserver:1.6.3          "dotnet BTCPayServer…"   6 minutes ago   Up 6 minutes                                                                                                                                                   btcpay-server_web_1
b6c9f82d9e61   nicolasdorier/nbxplorer:2.3.33           "dotnet NBXplorer.dll"   7 minutes ago   Up 6 minutes                             

```

Bug? documentation error? I'm not sure how to fix it atm

**Comment by urcheon2022** [comment]
nevermind... a restart and/or installing core lightning helped

**Comment by nevets963** [comment]
@urcheon2022 It sounds like your Bitcoin node might not have been working at the time. If you got this resolved. Are we OK to close this issue?

**Comment by urcheon2022** [comment]
> @urcheon2022 It sounds like your Bitcoin node might not have been working at the time. If you got this resolved. Are we OK to close this issue?

yes, go ahead, I am not able to replicate the issue
