### ISSUE TITLE
Update pihole to 2022.09.2

### ISSUE THREAD

**Issue by JamDaBam** [getumbrel/umbrel-apps#142]
Pleases update the docker image to the latest of [2022.09.2](https://hub.docker.com/layers/pihole/pihole/2022.09.2/images/sha256-533523ece86c4b45d0944c754e31521f8dd1e904da12531bfc0e46ff241ae721?context=explore)

greetings.

**Comment by nevets963** [comment]
@JamDaBam The latest version of Pi-Hole just went live. It may take up to 15 mins for it to appear as on update on your Umbrel.
