### ISSUE TITLE
[Update Request] - Invidious v2.20240825.2

### ISSUE THREAD

**Issue by anthony-robin** [getumbrel/umbrel-apps#1425]
Latest Invidious version has been released last week but doesn't seem to be detected by the bot updater :robot: 

- Changelog for last main version: https://github.com/iv-org/invidious/releases/tag/v2.20240825
- Latest bug release: https://github.com/iv-org/invidious/releases/tag/v2.20240825.2

Thank you :)

**Comment by nmfretz** [comment]
Thanks for the request @anthony-robin! We'll get Invidious updated.

**Comment by nmfretz** [comment]
The update is now live: https://github.com/getumbrel/umbrel-apps/pull/1428

FYI, looks like Invidious is currently working on fixing a known blocking issue:
https://github.com/iv-org/invidious/issues/4734
https://github.com/iv-org/documentation/pull/581

**Comment by anthony-robin** [comment]
Thank you very much for working on this request update so quickly :pray:
