### ISSUE TITLE
Core lightning Crash and Backup

### ISSUE THREAD

**Issue by ShahanaFarooqui** [getumbrel/umbrel-apps#1443]
A quick question: Does Umbrel have any provision/feature to auto-backup node data or HSM secret?

Reference Issue:
https://github.com/ElementsProject/lightning/issues/7617

**Comment by nmfretz** [comment]
@ShahanaFarooqui and I discussed this the other day in another forum, so including instructions below for others who find their way to this Issue.

Backups for umbrelOS are on the roadmap. In the meantime, data from any app needs to be manually backed up if desired.

Core Lightning Backup Documentation: https://docs.corelightning.org/docs/backup

At the time of this post, there are three Core Lightning files that can be backed up depending on your needs:
- hsm_secret
- emergency.recover
- lightningd.sqlite3 

`hsm_secret` is used to recover your on-chain funds. It does not recovery any in-channel funds.

`emergency.recover` and `lightningd.sqlite3` are used to recover your in-channel funds back on-chain.

> [!NOTE]
>  Please read the [Core Lightning Backup Docs](https://docs.corelightning.org/docs/backup) thoroughly before attempting recovery with these files to understand any limitations/risks and reach out to the Core Lightning team if anything is unclear.

### STEPS
1. Stop the Core Lightning App:
From your umbrelOS homescreen, right click on the Core Lightning app icon and select "Stop"

2. Change file permissions on the required Core Lightning data directory that contains the files we want to back up:
- From your umbrelOS homescreen, open up the Terminal by going to Settings > Advanced Settings > Terminal > umbrelOS
- From this terminal, copy-paste the following command and press `Enter`
```
sudo chmod 777 /home/umbrel/umbrel/app-data/core-lightning/data/lightningd/bitcoin/{,/*}
```

3. Copy the entire `/home/umbrel/umbrel/app-data/core-lightning/data/lightningd/bitcoin/` directory to your local computer

This folder contains the three files mentioned above (along with some others). You could copy the individual files instead, but this method is easiest.

> [!NOTE]
>  The following steps are to be carried out in a Terminal session on your LOCAL COMPUTER, not in the umbrelOS web terminal or while SSH'd into your umbrel.

- Create a directory on your local computer to store the files. For example, something like `core-lightning-backup`

- Open a Terminal on your computer. For example, on macOS you can open the Terminal app, or on Windows you can open Command Prompt or the PowerShell app.

- Navigate to the directory that you created previously. On macOS for example:
`cd /Users/nmfretz/core-lightning-backup`

- Copy over the directory from your Umbrel
Making sure you navigated to the correct directory in the step above, you can now run this command to copy over the files from your umbrel 
```
scp -r umbrel@umbrel.local:/home/umbrel/umbrel/app-data/core-lightning/data/lightningd/bitcoin/ ./
```

You should now have the following files on your local computer:

```
~/core-lightning-backup
❯ tree
.
└── bitcoin
    ├── accounts.sqlite3
    ├── ca-key.pem
    ├── ca.pem
    ├── client-key.pem
    ├── client.pem
    ├── emergency.recover
    ├── gossip_store
    ├── hsm_secret
    ├── lightningd.sqlite3
    ├── server-key.pem
    └── server.pem

2 directories, 11 files
```

4. Start the Core Lightning app up again
From your umbrelOS homescreen, right click on the Core Lightning app icon and select "Start"

**Comment by ShahanaFarooqui** [comment]
Thanks, closing the issue now.
