### ISSUE TITLE
Cloudflared apps are not accessible from the Umbrel dashboard

### ISSUE THREAD

**Issue by dennysubke** [getumbrel/umbrel-apps#1485]
Apps that are tunneled with Cloudlare cannot be accessed from the Umbrel dashboard. This can only be done by manually modifying the `umbrel-app.yml` file in `umbrel/app-data/cloudflaredumbrelapp/` in the line `path: "https://your.cloudflared.domain"`

A solution would be for the Cloudflare app to pass the domain to this file so that it can be accessed from the Umbrel Dashboard.

@Radiokot @smolgrrr

**Comment by Radiokot** [comment]
The Umbrel dashboard opens your apps locally, by your Umbrel's local hostname and the app port. They are always accessible, even if you have no Internet connection. Cloudflare Tunnel is a third-party app for Umbrel, it is unclear to me why it should change the behavior of the dashboard 🤔

**Comment by Radiokot** [comment]
And as far as I know, Umbrel dashboard itself doesn't work over a tunnel.

**Comment by dennysubke** [comment]
I think you misunderstood me or I expressed myself incorrectly. 

It is clear to me that the Umbrel Dashboard opens the apps locally. But once a Clouflare tunnel is created, they are no longer accessible directly from the dashboard. The path stored in the respective app still points to the local path. 

By setting up a Cloudflare tunnel, access is only possible via the respective domain (my.tunneled.domain) and no longer via the button in the dashboard.

![Screenshot 2024-09-16 221107](https://github.com/user-attachments/assets/0373a779-9a9d-4158-8f57-df4a59dbedc5)

**Comment by dennysubke** [comment]
> And as far as I know, Umbrel dashboard itself doesn't work over a tunnel.

Is possible. I tried it. 😎

**Comment by Radiokot** [comment]
What error or status code do yoy get if you access an app by local hostname and port?

**Comment by dennysubke** [comment]
I think I know what the problem is. It depends on the configuration in Nextcloud. HTTPS is enforced. The path is therefore changed to http**s**://umbrel.local:8081.

![grafik](https://github.com/user-attachments/assets/8ffbf23a-4126-4fbb-a4a9-febcc5876772)

http://umbrel.local:8081 still works. I hadn't tried that before and didn't notice it. 

Then I probably only have the fiddly solution of changing the umbrel-app.yml file. 😄

**Comment by Radiokot** [comment]
Sure, if you adjust config of the particular app to make it work with custom domain and HTTPS, this could make the app inaccessible from the local network. But this is not what the tunnel app does to other apps in general.

**Comment by dennysubke** [comment]
Then it cleared up. 

By default, it would still be better if Umbrel provided a self-signed SSL certificate to secure the web interface via HTTPS. (Like Portainer for example)
