### ISSUE TITLE
[Bug] lightning lnd -> lnd.conf

### ISSUE THREAD

**Issue by jjmmbb** [getumbrel/umbrel-apps#1693]
If you add allow_self_payment=true on the lnd.conf the lnd doesn't start.

**Comment by nmfretz** [comment]
Hey @jmmbb, `allow_self_payment` is not a config option, so LND will fail to start when it encounters something invalid in the conf file. That looks like a flag that you would pass in with an `lncli` command.

Are you thinking of `allow-circular-route=true`?
https://github.com/lightningnetwork/lnd/blob/22ae3e5ddd2abc7b06302b17a9368b4aa191aec7/sample-lnd.conf#L517-L519
```
; If true, our node will allow htlc forwards that arrive and depart on the same
; channel.
; allow-circular-route=false
```

If so, you can toggle this setting on from Advanced Settings in the Lightning Node app:
<img width="738" alt="image" src="https://github.com/user-attachments/assets/b2e4575c-99d3-4f8a-8186-9d438a23f3cd">

**Comment by jjmmbb** [comment]
> Hey @jmmbb, `allow_self_payment` is not a config option, so LND will fail to start when it encounters something invalid in the conf file. That looks like a flag that you would pass in with an `lncli` command.
> 
> 
> 
> Are you thinking of `allow-circular-route=true`?
> 
> https://github.com/lightningnetwork/lnd/blob/22ae3e5ddd2abc7b06302b17a9368b4aa191aec7/sample-lnd.conf#L517-L519
> 
> ```
> 
> ; If true, our node will allow htlc forwards that arrive and depart on the same
> 
> ; channel.
> 
> ; allow-circular-route=false
> 
> ```
> 
> 
> 
> If so, you can toggle this setting on from Advanced Settings in the Lightning Node app:
> 
> <img width="738" alt="image" src="https://github.com/user-attachments/assets/b2e4575c-99d3-4f8a-8186-9d438a23f3cd">
> 
> 
> 
> 

Got it. Thank you so much for explaining. I just need to receive payments between local lndhub users.
