### ISSUE TITLE
[Bug] ItchySats doesn't start after install

### ISSUE THREAD

**Issue by jjmmbb** [getumbrel/umbrel-apps#1708]
itchysats_app_proxy_1  | Error waiting for port: "The address 'itchysats_web_1' cannot be found"

**Comment by nmfretz** [comment]
Thanks for reporting @jjmmbb. Unfortunately, it looks like ItchySats is an unmaintained project now and is no longer functional at all:
https://github.com/get10101/itchysats

I have removed it from the app store: https://github.com/getumbrel/umbrel-apps/pull/1741
