### ISSUE TITLE
Public pool broken after Bitcoin Node update v28

### ISSUE THREAD

**Issue by Rob0xFF** [getumbrel/umbrel-apps#1715]
Cannot connect my miner to public pool any more, due to a change of a return value: Error getmininginfo jsonrpc field must be a string

**Comment by dennysubke** [comment]
In Bitcoin Core 28.0, there’s a notable change: the JSON-RPC server now supports JSON-RPC 2.0, allowing it to recognize JSON-RPC 2.0 requests and respond in strict compliance with the specification.

As a result, the Public Pool may require an update to ensure compatibility with the new JSON-RPC server. 

@nmfretz Can you take a look at that?

**Comment by nmfretz** [comment]
Hey, a Public Pool update just went live with a compatibility fix for Core v28:
https://github.com/getumbrel/umbrel-apps/pull/1726

Let me know if this gets you back up and running!

**Comment by Rob0xFF** [comment]
Hey, we are back and running. Thanks for the fast fix!

**Comment by nmfretz** [comment]
Excellent, thanks for confirming @Rob0xFF.

Closing.

**Comment by dennysubke** [comment]
Wow! That was quick. Everything is working perfectly again now! 😃
