### ISSUE TITLE
Error waiting for port: "The address 'albyhub_server_1' cannot be found"

### ISSUE THREAD

**Issue by Evil-Me** [getumbrel/umbrel-apps#1728]
I´ve installed the Alby Hub on my Umbrel node and get these error over and over again. The app won´t start at all. What can i do about this?

Error waiting for port: "The address 'albyhub_server_1' cannot be found"

Thanks a lot for your help.

**Comment by Atrytonopsis** [comment]
What was the fix? I'm having this issue and can't find nothing!?

**Comment by al-lac** [comment]
Hey @Atrytonopsis,

could you provide the docker logs for the app? This would make it a lot easier to help you out here.

**Comment by Atrytonopsis** [comment]
[umbrel_albyhub_2025-11-21_17-41.log](https://github.com/user-attachments/files/23690937/umbrel_albyhub_2025-11-21_17-41.log)

sorry not sure if this is what you mean.... im an absolute noob and trying to learn as i go.

**Comment by Atrytonopsis** [comment]
LND node needed to be set up and running... eye roll... sorry
