### ISSUE TITLE
Update to pi-hole failed

### ISSUE THREAD

**Issue by olwe1** [getumbrel/umbrel-apps#175]
Hello I just did the recent update to pi-hole 2022.09.4. Then the pi-hole icon app stayed in "starting" for hours.
I decided to remove the app then install it again but it stays stuck in "installing" status in the app store.

There's no pi-hole docker container with `docker ps -a`

Poke @mccolister1017

**Comment by nevets963** [comment]
@olwe1 If you're happy to uninstall/install again. Could you try via SSH:

```
sudo ~/umbrel/scripts/app uninstall pi-hole
```

And then:
```
sudo ~/umbrel/scripts/app install pi-hole
```

And post back the logs from when you install it again using the above command?

**Comment by olwe1** [comment]
> All good on my side, remember don't use pi-hole DNS before the update just cut it on your network. It will allow you to install Pi-hole or the update just make sure your DNS is not Pi-hole before the update or install.

Off course, I change the `nameserver` from `/etc/resolv.conf` to a distant one and it works. Thank you and sorry for such a mistake. :pray:
