### ISSUE TITLE
Command to clear repos dir

### ISSUE THREAD

**Issue by woofbotapp** [getumbrel/umbrel-apps#178]
I wanted to test the v0.4.0 of my app on the same Umbrel device that I used before to test v0.3.0 in the past.
The master branch in my https://github.com/woofbotapp/umbrel-apps repo has gone through some "reorg" because the previous PR was accepted with changes and not as-is.
I realized that the `sudo ./scripts/repo update` fails because of some git collision during an internal `git pull`, so I called `./scripts/repo set https://github.com/getumbrel/umbrel-apps`, deleted the `./repos/https---github-com-woofbotapp-umbrel-apps` dir, called `./scripts/repo set https://github.com/woofbotapp/umbrel-apps` again and then `./scripts/repo update` succeeded (The repo was downloaded from scratch again).

Would be nice to have some `./scripts/repo delete-cached-repos` command that would first make sure that the current repo is `./repos/https---github-com-getumbrel-umbrel-apps`, and then delete all the other cached repos.

Thanks!

**Comment by nevets963** [comment]
@woofbotapp Yes I notice the same issue for several apps and I simply delete the repo like you do. I'm hoping to address this in the next Umbrel version.

Btw, you can save 1 command by running:
```
./scripts/repo checkout https://github.com/woofbotapp/umbrel-apps
```

This internally calls `set` and then runs `update`, but it also supports a branch name, e.g.
```
./scripts/repo checkout https://github.com/woofbotapp/umbrel-apps#v4.0
```

**Comment by nmfretz** [comment]
Closing this Issue because the dev testing process for apps has changed with the release of umbrelOS 1.x:
https://github.com/getumbrel/umbrel-apps?tab=readme-ov-file#3-testing-the-app-on-umbrel
