### ISSUE TITLE
[Update Request] - Invidious v2.20241110.0

### ISSUE THREAD

**Issue by anthony-robin** [getumbrel/umbrel-apps#1802]
Invidious is broken on Umbrel for weeks because of changes made by Youtube on their backend :(
Last Invidious release from two days ago does not yet fix the videos playing but fix some other crashes such as the channel page that returns 400 error.

Could the Invidious app be updated on Umbrel to the [latest release](https://github.com/iv-org/invidious/releases/tag/v2.20241110.0) to bring back, at least, a little bit more stability ?

Thank you :)

**Comment by nmfretz** [comment]
Thanks for the request @anthony-robin. Always frustrating when youtube changes result in invidious breaking 😢.

The latest update is now live: https://github.com/getumbrel/umbrel-apps/pull/1803

**Comment by anthony-robin** [comment]
@nmfretz Thank you for the very quick upgrade :)
