### ISSUE TITLE
Update BTCPay Server to 2.0.3, critical vulnerability

### ISSUE THREAD

**Issue by ElucGeek** [getumbrel/umbrel-apps#1811]
I'm holding the update of BTCPay to  version 2.0.1 on Umbrel as the version 2.0.2 fix a critical vulnerability. Also version 2.0.3 is already out and have important changes and fix for boltcards usage.

How can we speedup the update on Umbrel app store?

**Comment by ElucGeek** [comment]
Ok It's updated thanks!

**Comment by nmfretz** [comment]
Thanks for the ping on this @ElucGeek! Sorry for the delay, we had our heads down on the recent beta launch
