### ISSUE TITLE
inquiry on activity for this application.

### ISSUE THREAD

**Issue by jimbrend** [getumbrel/umbrel-apps#1924]
Is Nitter being updated?

I was just clicking around, wondering,

You know, cuz ppl ask all the time that question, seems to be a high contact driver, gets a tad ridiculous at some point too, perhaps some diminishing returns in that regard to products/teams/companies, I'll go delve deeper into my own thoughts on that alone, 

Anyways,

Thanks to the awesome efforts of Umbrel team, they all deserve medals in my book, 

Cheers friends! [🥂](https://emojipedia.org/clinking-glasses) 

Oh, ha funny, that was right from google, emojipedia seems to be the way to go!

Thank you.

**Comment by jimbrend** [comment]
Would ya look at that, 

Yeah, I was just thinking about watching out for the redirects in Nitter, if you install it, perhaps some kind of warning?

i don't know, i guess machines are really no match for men?

Ok deep philosophical Jim outskis, peace out.

**Comment by al-lac** [comment]
Yeah there does not seem to be an update for Nitter. 

Twitter / X does not allow public access anymore without an account and rate limits the API. 

Probably makes sense to remove the app from the store @nmfretz.

**Comment by nmfretz** [comment]
Ya, agreed @al-lac. I've had this one on the list to remove for a while.

Removed here https://github.com/getumbrel/umbrel-apps/pull/1949.

Thanks guys.
