### ISSUE TITLE
[App Request] immish

### ISSUE THREAD

**Issue by abeldotam** [getumbrel/umbrel-apps#1984]
Hey, it could be awesome to have **Immish** on Umbrel! :)
👉 https://immich.app/ 

That's a very cool iPhoto alternative, open source and self hosted, in very active development, but it's already great.
You can have a look here: https://demo.immich.app/

Eventually, a setup with immish + cloudflare tunnels would be awesome.

Cheers,
Abel

**Comment by dennysubke** [comment]
It is already available and can be downloaded from the AppStore.

**Comment by abeldotam** [comment]
Apologies, indeed!
Closing the issue, then!
