### ISSUE TITLE
Update the Umbrel App Publishing Guide

### ISSUE THREAD

**Issue by IMPranshu** [getumbrel/umbrel-apps#201]
The guide is a bit old and needs to be updated. Will try to make some changes and open a PR soon.

**Comment by IMPranshu** [comment]
Getting this error after the `0.5.2` update

![image](https://user-images.githubusercontent.com/43396684/198513109-42f7c65c-e8ba-4612-ada5-85aaf8ede0d8.png)

**Comment by IMPranshu** [comment]
Cool. Nice to have this in the `One-page doc` as well.

**Comment by nevets963** [comment]
Ok, the docs are now updated 😄 https://github.com/getumbrel/umbrel-apps/#3-testing-the-app-on-umbrel

**Comment by IMPranshu** [comment]
Cool. Looks good. :+1:
