### ISSUE TITLE
Not able to install "Umbrel-dev" in Linux based system

### ISSUE THREAD

**Issue by IMPranshu** [getumbrel/umbrel-apps#204]
Need some other way to install umbrel-dev in Linux for testing purposes. the current instruction doesn't work on Linux.

**Comment by nmfretz** [comment]
Closing this Issue, because the dev process has changed with umbrelOS 1.x:
https://github.com/getumbrel/umbrel-apps?tab=readme-ov-file#31-test-using-a-linux-vm-on-your-local-machine-with-multipass
