### ISSUE TITLE
Don't delete app data on uninstall

### ISSUE THREAD

**Issue by guggero** [getumbrel/umbrel-apps#213]
Please make it possible to retain the data of an app when uninstalling it.
People regularly uninstall and re-install Lightning Terminal when they encounter any message that looks like an error. And then they wonder why their Pool account and order history are gone.
If that's not possible or infeasible, please at least add a big red (flashing?) warning message that uninstalling an app deletes its data.

**Comment by mayankchhabra** [comment]
Hey @guggero! Totally understand your concern. We do already have a warning in place:

<img width="421" alt="Screenshot 2022-10-25 at 7 50 53 PM" src="https://user-images.githubusercontent.com/10330103/197890093-6d4591ee-0337-4ed1-bc0f-4e36d5c1d090.png">

I'm afraid retaining data on uninstall would be an anti-pattern for an OS, and could be confusing for users. Eg. people uninstall apps for various reasons, and common reasons include usage of compute/storage by an app used that they don't really use. So the expectation of a user when deleting an app is also that it'd free up the disk space, and that re-installing it would set up everything from scratch.

**Comment by guggero** [comment]
Hmm... That's what I thought. But we have quite clear evidence that this warning message is more or less ignored or its implications not understood by many users.

Would it perhaps be a possibility that each app has the ability to define its own warning message in the manifest so we could add some more information about needing to run account recovery upon re-install? And maybe even a boolean flag in the manifest that prompts the user to check a checkbox that reads "Yes, I am sure I want to proceed".

**Comment by jaonoctus** [comment]
> And maybe even a boolean flag in the manifest that prompts the user to check a checkbox that reads "Yes, I am sure I want to proceed".

@guggero agreed

**Comment by dstadulis** [comment]
Wanted to bump this thread as Umbrel users frequently encounter this UX flow of their Umbrel machines deleting their Pool account data.  Currently the remedy involves walking the user through SSH'ing into their Umbrel which seems to defeat the purpose of the smooth UX Umbrel normally provides.

**Comment by mayankchhabra** [comment]
Thanks guys, we'll fine tune the wording in the next Umbrel release and try to make the implications more clear. If the issue still persists, we can definitely explore the idea @guggero suggested!

**Comment by xjmzx** [comment]
Would be great if umbrel had a UX/user-friendly method for stopping apps (when they hog too much ram, e.g mempool, elements.) It's problematic for users when docker containers might break other running apps with dependencies or remove an entire blockchain.

If not possible, perhaps warn users that their hardware might struggle with too many concurrent resource hungry processes.

**Comment by nmfretz** [comment]
> Thanks guys, we'll fine tune the wording in the next Umbrel release and try to make the implications more clear. If the issue still persists, we can definitely explore the idea @guggero suggested!

Wording was updated in umbrelOS 0.5.4:

<img width="426" alt="image" src="https://github.com/getumbrel/umbrel-apps/assets/85373263/3cb7350f-b112-4ff7-9a20-bbbcc2fa8800">

And maintained in umbrelOS 1.x:

<img width="497" alt="image" src="https://github.com/getumbrel/umbrel-apps/assets/85373263/f007e982-c855-41dc-8f2a-9380bbe890a4">

Closing this issue, but please reopen if this issue persists despite this change.
