### ISSUE TITLE
Tallycoin-connect stuck on Starting...

### ISSUE THREAD

**Issue by IMPranshu** [getumbrel/umbrel-apps#228]
![image](https://user-images.githubusercontent.com/43396684/198369826-d3bb40f7-e050-4fdc-a15d-4c1fcdf9502d.png)

**Comment by nevets963** [comment]
Looking at the icon, it looks an issue with Tallycoin Connect ?

If an app is stuck starting, then I would suggest taking a look at the container logs.

**Comment by IMPranshu** [comment]
Sorry, my bad! Will look into the logs

**Comment by IMPranshu** [comment]
While going through the logs found this 
```
tallycoin-connect_tor_server_1   Up 3 hours
tallycoin-connect_web_1          Restarting (1) 34 seconds ago
tallycoin-connect_app_proxy_1    Up 3 hours
```

**Comment by nevets963** [comment]
@IMPranshu Were you able to resolve this issue? If so, can I close this issue?
