### ISSUE TITLE
Satsale is just loading in browser

### ISSUE THREAD

**Issue by IMPranshu** [getumbrel/umbrel-apps#230]
![image](https://user-images.githubusercontent.com/43396684/198369949-e29c1738-464d-4ed3-aed2-b6aeb3bdea63.png)

**Comment by nevets963** [comment]
Are there any interesting logs from the Satsale container?

**Comment by IMPranshu** [comment]
How to get the logs? It is in my RasPi. Should I SSH into it and extract the logs?

**Comment by IMPranshu** [comment]
Nothing strange in the logs. But the app this not opening

**Comment by nevets963** [comment]
Ok, I would suggest you contact the app developer. Their support url is: https://github.com/nickfarrow/SatSale/issues

**Comment by nickfarrow** [comment]
Hmm strange, so nothing in the logs? Is your LND version up to date?

Does `192.168.1.21:5000/` fail to load also?

**Comment by IMPranshu** [comment]
It was endlessly loading. No error whatsoever

**Comment by nickfarrow** [comment]
Is it still? My guess would be one of the LND bugs prevented SatSale from contacting LND and loading

**Comment by nevets963** [comment]
@IMPranshu Were you able to resolve this issue? If so, can I close this issue?
