### ISSUE TITLE
BTCPayServer Thinks It's in HTTP Context

### ISSUE THREAD

**Issue by leesalminen** [getumbrel/umbrel-apps#236]
When attempting to use BTCPayServer on Umbrel in clearnet (say using Cloudflare Tunnel or Tailscale), BTCPayServer still thinks it's being connected to over HTTP (as opposed to HTTPS). Upon attempting to log in, you are presented with this error message from BTCPayServer: "You cannot login over an insecure connection. Please use HTTPS or Tor."

This is happening due to a lack of proper headers being passed by the app_proxy. Namely, the `X-Forwarded-Proto` header.

Proposed solution: introduce an nginx container to the BTCPayServer app that sits between `app_proxy` and `btcpayserver` so it can set the appropriate headers.

**Comment by nevets963** [comment]
@leesalminen The App Proxy will forward headers from its upstream if told to do so for security reasons. We addressed this issue in Umbrel v0.5.1 and provided some instructions here: https://github.com/getumbrel/umbrel/issues/1428#issuecomment-1184584190

**Comment by leesalminen** [comment]
Confirmed this issue is not valid, closing.
