### ISSUE TITLE
User having issues connecting to sphinx-relay

### ISSUE THREAD

**Issue by kevkevinpal** [getumbrel/umbrel-apps#245]
He was having issues since the server couldn’t be reached using the conection code Umbrel was providing. Finally I decoded that string and found that it had a port (3300) in the ip. I tried without the port and it worked. I sent him a new encoded string with the IP without the port. 

I think this file is where we need to make that change
https://github.com/getumbrel/umbrel-apps/blob/master/sphinx-relay/docker-compose.yml#L20

**Comment by Evanfeenstra** [comment]
If `PUBLIC_URL` just equals `$APP_HIDDEN_SERVICE` that will fix this issue for tor users. Are all Umbrel's running with tor though?

**Comment by nevets963** [comment]
Hey folks, this bug has been address via this PR: https://github.com/getumbrel/umbrel-apps/pull/248

You should see an app update in about 5 minutes.

**Comment by kevkevinpal** [comment]
> Hey folks, this bug has been address via this PR: #248
> 
> You should see an app update in about 5 minutes.

awesome thanks, closing this issue

**Comment by kevkevinpal** [comment]
reopening this was reported

after upgrading his Umbrel relay to “2.2.10-hotfix-1” all the apps lost connection to the server. So something breaks there or the IP changed or something.

**Comment by kevkevinpal** [comment]
where is that export used? we noticed before the hotfix that there was a port appended to the tor URL but after removing the port it was able to connect

**Comment by nevets963** [comment]
What do you mean by `all the apps lost connection to the servers`?

This export is used within Umbrel that allows extra ports to be exposed via the app's default Tor server. The PR added port `3300` so that it's accessible via Tor. I tested this using my iOS Sphinx app and could get it to connect.

**Comment by kevkevinpal** [comment]
Oh I think I see why you didn't remove the port you made it open, the user removed the port to make it work.

I can let him know to add back the port and it should work

Thanks @nevets963
