### ISSUE TITLE
Snowflake doesn't show hourly statstics

### ISSUE THREAD

**Issue by mariocynicys** [getumbrel/umbrel-apps#252]
![image](https://user-images.githubusercontent.com/56920956/200035057-88af28e4-80f2-4624-9b8c-577d55d284ca.png)

Umbrel Version: 0.5.3
OS: Ubuntu 20.04
Brwoser: Firefox

**Comment by nevets963** [comment]
@mariocynicys Is this problem still persisting?

When everything is working, you should see logs similar to:
```
2022/11/06 17:01:40 In the last 1h0m0s, there are 0 connections. Traffic Relayed ↑ 0 B, ↓ 0 B.
```

**Comment by mariocynicys** [comment]
@nevets963 nah still showing grep's output.
It used to work fine (report the same output you have) a month ago. Now it doesn't.

**Comment by mariocynicys** [comment]
I am not even sure if the app is working or not.
Before I shut down my instance in 9/26, snowflake caused a pattern where daily downloads were close to daily uploads (disturbed by other running applications):
![image](https://user-images.githubusercontent.com/56920956/200185713-4f25a7f4-9fb7-4c49-969c-b8d06a28b42e.png)

After firing my instance back up in 10/22, this pattern no longer holds. Which makes me thing snowflake isn't running.

**Comment by nevets963** [comment]
Strange, as that log was from Snowflake that I installed 5 mins before posting.

Are you able to post logs directly from the snowflake container here?

**Comment by mariocynicys** [comment]
Solved!
I uninstalled snowflake, rebooted umbrel then reinstalled snowflake and now everything working fine.
![image](https://user-images.githubusercontent.com/56920956/200188241-e82ce806-f1cd-4d1f-96fb-52cc54a48dbf.png)

keywords: grep standard input binary file matches
