### ISSUE TITLE
Customizing bitcoin node settings

### ISSUE THREAD

**Issue by PlebeiusGaragicus** [getumbrel/umbrel-apps#277]
https://github.com/getumbrel/umbrel-apps/blob/e2796a083c23a82a4002466392c48ab8e9b275b3/bitcoin/exports.sh#L57-L78

I'm wondering how these settings could be user-customizable.  Of course, this could potentially break apps that rely on bitcoin - but the user should be responsible for managing their apps.

This would, for example, allow someone to run a pruned node.

**Comment by aphex3k** [comment]
you can configure your bitcoin instance by modifying the `bitcoin.conf` file in the bitcoin apps app-data directory.

**Comment by jaonoctus** [comment]
@PlebeiusGaragicus In order to run a pruned node, see:

https://youtu.be/qyAtye2NWGc

> Remember that apps like Electrum, Mempool Explorer and some others will not work because they require `txindex=1`

**Comment by nevets963** [comment]
@PlebeiusGaragicus Before Christmas we released an update for the Bitcoin app that allows more user-customisation through the UI (avoiding SSH); for example, pruning can now be controlled easily. More details can be found here: https://twitter.com/umbrel/status/1605906942555148288

Does this update close this issue?

**Comment by PlebeiusGaragicus** [comment]
This is a good start.  I think the goal should be to allow for every setting to be adjusted - whatever the user wants.  Hopefully there can also be other bitcoin core versions on the marketplace so people would be able to write their own version with their own UI.  And hopefully the other features wouldn't break when a user changers these settings.  Something to shoot for.  Until then people will need to SSH in to adjust things and otherwise hack their way into getting their chosen app to work.
