### ISSUE TITLE
Unable to sync Trilium Notes with desktop instance

### ISSUE THREAD

**Issue by rworkm** [getumbrel/umbrel-apps#292]
Installed Trilium via Umbrel store.  Installed Trilium desktop and selected the setup option "I have a server instance already, and I want to set up sync with it."
I input the umbrel address and port for Trilium, e.g. http://192.168.0.100:3779 and password. This error is returned:

> Sync setup failed: Request to get http://192.168.0.100:3779/api/setup/sync-seed failed, error: Unexpected token < in JSON at position 0

From examining the docker containers list it appears there is a Trilium App container and a Trilium Server container.  I suspect this has something to do with it.

**Comment by IMPranshu** [comment]
Yeah. You are right. Currently, this feature is not available to sync outside Umbrel.

**Comment by nevets963** [comment]
Thanks for reporting this! The issue was; the Umbrel App Proxy was protecting the Trilium API. This PR https://github.com/getumbrel/umbrel-apps/pull/298 resolves the issue. You should see an update for Trilium on your Umbrel in the next ~5 mins.

**Comment by rworkm** [comment]
Works now, thank you!
