### ISSUE TITLE
Snowflake doesn't route?

### ISSUE THREAD

**Issue by mariocynicys** [getumbrel/umbrel-apps#315]
A couple of weeks past fixing my issue in #252, I see the logs fine now but no traffic is being relayed what so ever (or at least this is what the UI says):
![image](https://user-images.githubusercontent.com/56920956/204820465-2b87a35b-0f63-485a-9fa7-ef6d848cb60b.png)

And this looks like this has been the case for so long (since fixing my issue in #252).
There used to be some numbers written in these logs before, like:
`DATE TIME In the last 1h0m0s, there are 42 connections. Traffic Relayed ↑ 2 GB, ↓ 2 GB.`

**Comment by mariocynicys** [comment]
Also looks like the anti-pattern in https://github.com/getumbrel/umbrel-apps/issues/252#issuecomment-1304852979 is repeating (daily download size isn't anywhere near upload size). I think it's not a UI issue then.

**Comment by aphex3k** [comment]
My understanding is that there is no guarantee that your proxy will route traffic. I see intermittent pause of routing but it picks up eventually and then pauses again...

**Comment by LeoSpyke** [comment]
For my own experience, I had to wait 5-6 days after the initial setup before my node started routing and actually I see almost stable amounts of connections and data transferred every hour.

**Comment by mariocynicys** [comment]
> For my own experience, I had to wait 5-6 days after the initial setup before my node started routing and actually I see almost stable amounts of connections and data transferred every hour.

Just re-checked it and it now does indeed route now, but took at least 30 days for me to actually start routing.
