### ISSUE TITLE
Application Request: qBittorrent

### ISSUE THREAD

**Issue by stpnwf** [getumbrel/umbrel-apps#328]
Can you please add [qBittorrent](https://www.qbittorrent.org/) as an Umbrel app? Transmission is nice, but qBit has a better web interface with the option to install third party alternate Web UIs. And also has more features.

Unsure if this is helpful but this is linuxServer.io's qBittorrent container: https://hub.docker.com/r/linuxserver/qbittorrent/#!

**Comment by ASOwnerYT** [comment]
#468
