### ISSUE TITLE
Should simple-torrent and transmission write to `UMBREL_ROOT` instead of `APP_DATA_DIR` so that jellyfin can read them?

### ISSUE THREAD

**Issue by johnpc** [getumbrel/umbrel-apps#349]
Apps like simple-torrent download files to `${APP_DATA_DIR}/data/download`: https://github.com/getumbrel/umbrel-apps/blob/master/simple-torrent/docker-compose.yml#L18

But apps like jellyfin read files from `${UMBREL_ROOT}/data/storage/downloads`: https://github.com/getumbrel/umbrel-apps/blob/master/jellyfin/docker-compose.yml#L19

Wouldn't it be easier for jellyfin to consume content from simple-torrent and transmission if they wrote their data to  `${UMBREL_ROOT}/data/storage/downloads` instead of  `${APP_DATA_DIR}/data/download` so that they could share data between these apps?

If not, how am I supposed to share this data? Manually move files from folders accessed by one container to folders accessible to the other?

**Comment by mayankchhabra** [comment]
Hey @johnpc! Thanks for bringing this up. You are right. This doesn't make sense. 

SimpleTorrent was introduced in our app store before we implemented a "shared" downloads directory. We're working on pushing out an update to SimpleTorrent that uses the new shared downloads directory by default, while automatically migrating existing users' content in  `simple-torrent/data/download` to `${UMBREL_ROOT}/data/storage/downloads`.
