### ISSUE TITLE
Can you add sabnzbd to Umbrel store please?

### ISSUE THREAD

**Issue by Lethargy9117** [getumbrel/umbrel-apps#350]
Here is their Github address, please add to Umbrel store.

https://github.com/sabnzbd/sabnzbd

**Comment by nmfretz** [comment]
Thanks for this request @Lethargy9117. SABnzbd is now available on the Umbrel App Store!

Closed by https://github.com/getumbrel/umbrel-apps/commit/b5c63889caecf8fb4501fc125ec44b11f00095e7
