### ISSUE TITLE
Update documentation regarding using custom repo

### ISSUE THREAD

**Issue by Asone** [getumbrel/umbrel-apps#358]
With the latest versions of umbrel the way custom applications should be mounted to be tested on local node has changed.

The `repo` script seems to now expect a clone of a custom app store instead of a fork of current repo as per the [following code](https://github.com/getumbrel/umbrel/blob/master/scripts/repo#L226-L243). 
Current doc still mentions the old process which is confusing. 

The doc should be updated to be adequate with the expected process to load custom apps and repos.

**Comment by nevets963** [comment]
Thanks for the feedback - I'll work on improving the docs!

Re:
> The repo script seems to now expect a clone of a custom app store instead of a fork of current repo as per the [following code](https://github.com/getumbrel/umbrel/blob/master/scripts/repo#L226-L243).

The `repo` script works with both forked app stores and community app stores. Developers that want to push app updates into the official Umbrel App Store, would fork our app store repo (this repo), make the changes and then send us a PR. For those that want to run their own Community App Store, they can follow this guide: https://github.com/getumbrel/umbrel-community-app-store

**Comment by Asone** [comment]
> The `repo` script works with both forked app stores and community app stores. Developers that want to push app updates into the official Umbrel App Store, would fork our app store repo (this repo), make the changes and then send us a PR. For those that want to run their own Community App Store, they can follow this guide: https://github.com/getumbrel/umbrel-community-app-store

I was using the `umbrel-apps` fork i had and everytime i tried to update i had the repo to be cloned then deleted due to the mentioned code block. 

I ended using a custom app store and moved the apps i added - which was quite quick - but thought this could be kind of confusing for other people

**Comment by nmfretz** [comment]
Closing this Issue since the dev process for testing apps has changed with the release of umbrelOS 1.0
