### ISSUE TITLE
How to run umbrel-bitcoin node in testnet

### ISSUE THREAD

**Issue by deb-dasit** [getumbrel/umbrel-apps#364]
Hi how to run umbrel-bitcoin in testnet. I followed the below steps, but the blocks are not getting synced.
1. After fresh installation, removed the .env, db/user.json, umbrel-seed/seed, statuses/configured files.
2. then executed `sudo NETWORK=testnet ./scripts/configure`
3. then  installed umbrel-bitcoin by `sudo ./scripts/app install bitcoin`
4. After this when navigating to the bitcoin node app, getting the below screen, the sync is not happening.
![image](https://user-images.githubusercontent.com/3907017/212112836-8f0e2837-4fb7-4881-bbac-78a3e6a48656.png)

**Also there's no error in the console, and the blocks and headers counts are 0.**
![image](https://user-images.githubusercontent.com/3907017/212114491-8f860ff6-f651-4699-a0bd-107863b7f5bf.png)

Can anyone help how to setup umbrel-bitcoin in testnet.
Am i doing something wrong anywhere?

**Navigating to the docker container (getumbrel/bitcoind), the bitcoin daemon is running in rpcport 8332. how can I run umbrel-bitcoin in 18332 port.**

**Comment by mayankchhabra** [comment]
Hey @deb-dasit! Apologies for the confusion. Changing the network to testnet is very simple now, no need to edit any configuration manually. Just click the "..." menu on the right of the "Connect" button > Advanced Settings > Network > Select testnet > Hit save and restart. That should be it!

**Comment by deb-dasit** [comment]
Okay thanks @mayankchhabra. Does changing the network also change the rpc ports? Likewise if using mainnet, 8332 port will be used, and if I change it to testnet will it change the port to 18332?

**Comment by deb-dasit** [comment]
Yes now it's syncing the test, but checking the bitcoind container, it's showing bitcoind daemon is running with rpcport 8332, can we change this port too, to 18332?

**Comment by nmfretz** [comment]
Hey @deb-dasit, the rpc and p2p ports are hardcoded to 8332 and 8333, such that they will work for any network that you choose to run on (mainnet, testnet, signet, regtest). Are you still having an issue that we can help with?
