### ISSUE TITLE
Can you add FireFly iii to the Umbrel AppStore

### ISSUE THREAD

**Issue by integer256** [getumbrel/umbrel-apps#375]
"Firefly III" is a (self-hosted) manager for your personal finances. It can help you keep track of your expenses and income, so you can spend less and save more.

More information here: 
https://github.com/firefly-iii/firefly-iii/

**Comment by nevets963** [comment]
@integer256 We've just added Firefly III to the Umbrel App Store 😄 🚀  You should be able to see this in the Umbrel App Store in about 5 mins.

The PR was here: https://github.com/getumbrel/umbrel-apps/pull/378

**Comment by integer256** [comment]
Awesome, Thanks @nevets963
