### ISSUE TITLE
Add Ghostfolio to the Umbrel AppStore

### ISSUE THREAD

**Issue by integer256** [getumbrel/umbrel-apps#386]
It would be great to add the Ghostfolio App to the store. 

Ghostfolio is an open source wealth management software built with web technology. The application empowers busy people to keep track of stocks, ETFs or cryptocurrencies and make solid, data-driven investment decisions. The software is designed for personal use in continuous operation.

I am sure lot of users will benefit from it. As well, it already runs on Docker

**Comment by BeauAgst** [comment]
Hey @integer256, I just wanted to let you know that I thought I'd look at this for you. I've mostly set everything up, but need to deal with an issue within Ghostfolio itself

**Comment by dtslvr** [comment]
> Update: Fix has been merged, but we will need to wait for a new release before we can continue!

The new version has been released: [Ghostfolio v1.231.0](https://github.com/ghostfolio/ghostfolio/releases/tag/1.231.0)
