### ISSUE TITLE
Application Request - FreshRSS

### ISSUE THREAD

**Issue by rtcms** [getumbrel/umbrel-apps#414]
Add https://github.com/FreshRSS/FreshRSS to umbrel-apps

**Comment by integer256** [comment]
+ 1

**Comment by IMPranshu** [comment]
@rtcms try it out. Hope it helps

**Comment by nmfretz** [comment]
Thanks for the request @rtcms. FreshRSS is available in the Umbrel App Store thanks to @IMPranshu!

Closed by https://github.com/getumbrel/umbrel-apps/commit/0b8898f9030777cfd6d9dfd0d9a4312df33d79f3
