### ISSUE TITLE
Duplicated export lines in lndg app

### ISSUE THREAD

**Issue by woofbotapp** [getumbrel/umbrel-apps#423]
Noticed in:

https://github.com/getumbrel/umbrel-apps/blob/ec596511cf732f7f3b8c3c8bdf8de5bac9dde6b7/lndg/exports.sh#L3-L4

**Comment by nevets963** [comment]
@woofbotapp Thanks for reporting! This is resolved in commit https://github.com/getumbrel/umbrel-apps/commit/e946af0ae0a9164d0c61842bab1a89bb8f4574cc
