### ISSUE TITLE
update Jellyfin version

### ISSUE THREAD

**Issue by mmattbtw** [getumbrel/umbrel-apps#424]
i'm trying to use the Jellyfin Trakt plugin, and in the current version Umbrel is using `10.8.4`, it's bugged and unusable, and can be fixed by updating (according to https://github.com/jellyfin/jellyfin-plugin-trakt/issues/185). is there any way to update it? i would send a PR to do it myself, but i gave up lol

**Comment by nmfretz** [comment]
Hey @mmattbtw a Jellyfin update was just pushed to the Umbrel app store. Can you please let me know if this fixes the Trakt plugin issue for you 🤞

**Comment by mmattbtw** [comment]
worked perfectly! thanks y’all 🤠

**Comment by nmfretz** [comment]
Excellent, thanks for letting me know. And thanks to @Xosten for the update PR.
