### ISSUE TITLE
Error when installing nostr-relay

### ISSUE THREAD

**Issue by derWahnsinn** [getumbrel/umbrel-apps#433]
Nostr-Relay installation fails with the following error:

````
root@umbrel:~/umbrel/scripts# ./app install nostr-relay
Installing "nostr-relay" from: https://github.com/getumbrel/umbrel-apps.git
Setting up data dir for app nostr-relay...
sending incremental file list
./
docker-compose.yml
umbrel-app.yml
data/
data/relay/
data/relay/config.toml
data/relay/db/

sent 7,451 bytes  received 92 bytes  15,086.00 bytes/sec
total size is 7,100  speedup is 0.94
Pulling images for app nostr-relay...
Pulling app_proxy ... done
Pulling relay     ... done
Pulling web       ... extracting (100.0%)

ERROR: for web  failed to register layer: ApplyLayer exit status 1 stdout:  stderr: failed to Lchown "/app/node_modules/ast-types-flow/README.md" for UID 369884941, GID 1876110778 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /app/node_modules/ast-types-flow/README.md: invalid argument
ERROR: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: failed to Lchown "/app/node_modules/ast-types-flow/README.md" for UID 369884941, GID 1876110778 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /app/node_modules/ast-types-flow/README.md: invalid argument
````

Namespaces for this UID/GID should be in the range:

````
cat /proc/sys/user/max_user_namespaces
2147483647
````

/etc/subgid and /etc/subuid are both empty, Installation was performed under root user.

I have already tried adding a user "umbrel" with id "1000" and increase the range for user "umbrel" in /etc/subgid and /etc/subuid, but without any success.

Can anybody help?

**Comment by caasisaac** [comment]
I'm having the same error, umbrel is installed in a proxmox container Ubuntu 22.10(Create CT) but when I try to install the nostr-relay app I get the same error:
 ```
root@Umbrel:~/umbrel/scripts# ./app install nostr-relay
Installing 'nostr-relay' from: https://github.com/getumbrel/umbrel-apps.git
Setting up data dir for app nostr-relay...
sending incremental file list

sent 203 bytes  received 15 bytes  436.00 bytes/sec
total size is 7,100  speedup is 32.57
Pulling images for app nostr-relay...
Pulling web       ... extracting (100.0%)
Pulling app_proxy ... done
Pulling relay     ... done

ERROR: for web  failed to register layer: ApplyLayer exit status 1 stdout:  stderr: failed to Lchown "/app/node_modules/ast-types-flow/README.md" for UID 369884941, GID 1876110778 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /app/node_modules/ast-types-flow/README.md: invalid argument
ERROR: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: failed to Lchown "/app/node_modules/ast-types-flow/README.md" for UID 369884941, GID 1876110778 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /app/node_modules/ast-types-flow/README.md: invalid argument
```

**Comment by algotechio** [comment]
I have the same issue, but with `lnbits`.   I tried to install the app from the web interface and it was just hanging:

In `karen.log`, the error appears:

```
Installing 'lnbits' from: https://github.com/getumbrel/umbrel-apps.git
Setting up data dir for app lnbits...
sending incremental file list

sent 147 bytes  received 13 bytes  320.00 bytes/sec
total size is 2,333  speedup is 14.58
Pulling images for app lnbits...
Pulling app_proxy  ... done
Pulling web        ... extracting (100.0%)
Pulling tor_server ... done

ERROR: for web  failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /usr/local/lib/python3.10/site-packages/setuptools-65.5.1.dist-info: invalid argument
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /usr/local/lib/python3.10/site-packages/setuptools-65.5.1.dist-info: invalid argument
```

I am running in the following environment:  Unprivileged LXC container with Ubuntu 20.04 running on proxmox.

I suspect that the problem has to do with LXC and docker making call requiring system privileges.  I briefly looked at [lnbitsdocker/lnbits-legend:latest](https://hub.docker.com/layers/lnbitsdocker/lnbits-legend/latest/images/sha256-ea05dc398af946dd657122d79ab9de3e98fafb73370ed8d05ef830f4ecfb35d9?context=explore), but did not find anything that could cause this problem.

**Comment by nmfretz** [comment]
Hey All, sorry for the frustration. It looks like you are all running umbrelOS 0.5.x on top of custom debian/ubuntu systems, so this is likely related to specific debian/ubuntu configurations. umbrelOS 1.x is now a standalone operating system that installs directly onto your device’s internal storage, so these issues will no longer exist:
 
https://community.umbrel.com/t/how-to-update-from-umbrelos-0-5-to-umbrelos-1-1-on-linux-devices/16704

If you're still running 0.5.x and encountering issues with certain debian/ubuntu configurations please reach out to our official support via our [Website](https://umbrel.com/) and we can help troubleshoot.
