### ISSUE TITLE
Application Request: Vikunja

### ISSUE THREAD

**Issue by matiasvillaverde** [getumbrel/umbrel-apps#434]
https://github.com/go-vikunja/frontend

It would be great to have some productivity apps like a todo app

**Comment by IMPranshu** [comment]
@integer256 this app looks really cool. Will be opening a PR soon for your request. thanks!

**Comment by IMPranshu** [comment]
Opened a PR https://github.com/getumbrel/umbrel-apps/pull/694

**Comment by nmfretz** [comment]
Thanks for this request @matiasvillaverde. Vikunja is now available on the Umbrel app store thanks to @IMPranshu!
https://github.com/getumbrel/umbrel-apps/pull/694
