### ISSUE TITLE
Code-server terminal text completely obfuscated

### ISSUE THREAD

**Issue by SovNym** [getumbrel/umbrel-apps#446]
### Current behavior
👉 When using the code-server app by coder.com on Umbrel, opening the terminal results in completely obfuscated text that is unreadable. Each letter in the terminal appears as a rectangular block with various colors through it, making it impossible to read the text.

### Expected behavior
👉 The text in the terminal should be legible and not obfuscated, allowing users to read and use the terminal normally.

### Steps to reproduce
1. Install code-server app on Umbrel node
2. Connect via TOR
3. Open code-server app
4. Open terminal within the app

### Additional information
- Umbrel version: [insert Umbrel version here]
- code-server app version: [insert code-server app version here]

📷 Please find attached a screenshot of the obfuscated text in the terminal.

![Screenshot 2023-03-03 at 16 56 03](https://user-images.githubusercontent.com/126130575/222782113-f5596581-1c50-4066-aa8b-2a0e093f7857.png)

**Comment by nmfretz** [comment]
Hey @SovNym, thanks for bringing this to our attention. I was able to recreate your issue as described. It seems to only be happening over a TOR connection. I've got this on the list to look into for the next code-server app update

In the meantime, are you accessing over TOR for anonymity, or are you just trying to access your Umbrel remotely outside your local network so you can code from anywhere? If you are just trying to access remotely then a much faster and seemless experience would be to install the Tailscale app on your Umbrel and on any device that you would like to access your Umbrel from. This would allow you to connect and use code server without the TOR lag and terminal obfuscation issue.

**Comment by nmfretz** [comment]
Actually, I just found a workaround for you if you want to continue accessing code server over TOR:

In code-server settings, search `terminal integrated gpu acceleration` and set this to `canvas`. See working screenshot below.

**Comment by nmfretz** [comment]
Closed by https://github.com/getumbrel/umbrel-apps/issues/446#issuecomment-1454200925
