### ISSUE TITLE
[App Request] - Firefly Data Importer

### ISSUE THREAD

**Issue by fernando2h** [getumbrel/umbrel-apps#457]
Firefly on its own is great, but not very useful, as you have to add every transaction individually and manually. 

There is a Data Importer for it, but it seems a bit complicated to install. Personally, I don't have the knowledge necessary to do that by my own (yet). 

It would be great to see it installed either automatically when one installs Firefly, or as an independent app on the app store.

https://github.com/firefly-iii/data-importer

Cheers!

**Comment by nmfretz** [comment]
Thanks for this request @fernando2h. Firefly Data Importer is now available in the Umbrel App Store!

Closed by https://github.com/getumbrel/umbrel-apps/commit/a837d67a9a06d19787cc549007cd28c8772392cb
