### ISSUE TITLE
Home Assistant configuration file

### ISSUE THREAD

**Issue by kroese** [getumbrel/umbrel-apps#46]
I installed Home Assistant and tried to add an integration service, for which I needed to edit `configuration.yaml`.

After many failed attempts I discovered that Umbrel does not use the existing `configuration.yaml` in the`/config` folder, but instead uses a seperate one in the app folder.

However, all changes to that file will be constantly wiped out during restarts or app updates. 

So what can one do to work around this issue?

Maybe we can add a line to the main yaml to also include `/config/configuration.yaml` so that both files can be used.

**Comment by dcninja** [comment]
I had some success going into the docker image by command line, hoping next version will fix this

**Comment by nmfretz** [comment]
Apologies for this oversight. Recent versions of the Home Assistant app now properly binds and uses the default config pathway.
