### ISSUE TITLE
Snort does not recognize nos2x browser extension

### ISSUE THREAD

**Issue by rworkm** [getumbrel/umbrel-apps#471]
Using Brave browser or Opera browser.  
Installed Snort on Umbrel (installed on system running Debian).  Installed nos2x browser extension.

The Snort login page presents the login option, but will not accept the private key - "Can't login with private key on an insecure connection, please use a Nostr key manager extension instead"

It does not detect the extension when it is installed and gives the message - "Hmm, can't find a key manager extension.. try reloading the page." at the bottom of the page.

**Comment by ogunden** [comment]
Same issue with chromium on Ubuntu

**Comment by nmfretz** [comment]
Thanks for reporting guys. Can you please open an issue in the Snort repo so devs can address this: https://git.v0l.io/Kieran/snort/issues
