### ISSUE TITLE
Invoice Ninja download does not work

### ISSUE THREAD

**Issue by dentropy** [getumbrel/umbrel-apps#498]
I installed invoice ninja and tried generating and downloading an invoice and got various errors.

I am unable to generate an invoice from the invoice page,

When selecting "View PDF" I get a "XMLHttpRequest error.".

When selecting download I get redirected to a the umbrel servers hostname, which is not a problem, but it is missing the port. If I add the port to the URL the download works.

The "Print PDF" button on the invoice page produces an infinite loop.

Please note that the Invoice is rendered accurately at the bottom of the invoice page.

**Comment by cdmoss** [comment]
Me too. Looks like it might related to CORS:

![image](https://github.com/getumbrel/umbrel-apps/assets/40777533/00a77def-95dd-48ea-a268-6e7ecdb9f04f)

**Comment by nmfretz** [comment]
I have just updated Invoice Ninja and cannot recreate these issues using. I am able to view and download invoice pdfs without issue when accessing invoice-ninja via umbrel.local domain or IP address.

Closing. If anyone encounters issues related to this please reach out on our Discord for live help: https://discord.gg/y9bBm8ca
