### ISSUE TITLE
[Update Request] Gitea

### ISSUE THREAD

**Issue by kirkryan** [getumbrel/umbrel-apps#503]
Hi @ceramicwhite,

Is it possible to update Gitea to 1.19.1 as it contains important bug fixes and a major new functionality i.e. Gitea Actions (similar to Github Actions), Secrets and more.

## Breaking Changes

⚠️ Incorrectly documented default value for update checker ([#22084](https://github.com/go-gitea/gitea/issues/22084))

[cron.update_checker].ENABLED is true by default. Previously, the documentation indicated that it would be disabled by default, which was incorrect.

⚠️ Newly reserved username: gitea-actions ([#21937](https://github.com/go-gitea/gitea/issues/21937))

With the implementation of Gitea Actions (see below), Gitea needed a user to run the actions. The username gitea-actions was chosen and is thus now reserved. If a user with that name exists, an admin should rename them, i.e. using the admin panel.

⚠️ Remove DSA host key from Docker Container ([#21522](https://github.com/go-gitea/gitea/issues/21522))

The DSA host key has been removed from the OpenSSH daemon configuration file in the Docker container for Gitea. This change is a result of the deprecation of the DSA public key algorithm since OpenSSH >= 7.0. As a result, any client that uses DSA for authentication will no longer be able to connect to the Docker container. We recommend users to use a different public key algorithm such as RSA or ECDSA for authentication.

⚠️ Remove ReverseProxy authentication from the API ([#22219](https://github.com/go-gitea/gitea/issues/22219))

ReverseProxy-authentication was an insecure way of authenticating a user. Hence, it was dropped without replacement. Any user that relied on it must switch to basic or token authentication now.

⚠️ Remove [ui].ONLY_SHOW_RELEVANT_REPOS setting. ([#21962](https://github.com/go-gitea/gitea/issues/21962))

On the explore page, you can switch whether you only want to see relevant repos, or all repos. As this page already offers a link to switch between these two options, this setting only had a negligible effect and complicated the logic by a lot. Hence, it was dropped without replacement. You can now remove it from your app.ini if present.

⚠️ Restrict valid user names ([#20136](https://github.com/go-gitea/gitea/issues/20136))

Valid user names now follow the following rules:

allowed letters are -,., _, 0-9, a-z, A-Z
names must not start or end with -,., or _
names must not have consecutive -,., or _. (i.e. a-.b is illegal)
No action must be taken for existing users. This is only enforced for newly created users.

⚠️ Separate allowed units for normal repos and forks ([#22541](https://github.com/go-gitea/gitea/issues/22541))

Previously, fork repositories had all default units. Now, forks only enable code access and pull requests by default. If you want everything to behave like before, please set the setting [repository].DEFAULT_FORK_REPO_UNITS to the value of [repository].DEFAULT_REPO_UNITS.

⚠️ Support camel case for issue and code search when using Bleve ([#22829](https://github.com/go-gitea/gitea/issues/22829))

In order to be able to support queries that include camel case tokens, the indexes must be rebuilt. This is an automatic process that will be done on the first startup without any user interaction.

⚠️ Support commit description in the merge template ([#22248](https://github.com/go-gitea/gitea/issues/22248))

Previously, your whole default_merge_message template file was considered to be the commit title. Now, only the first line is the commit title, and the rest (from line 3 on) is the commit description, just like in normal commits.

##Highlights

🚀 Gitea Actions ([#21937](https://github.com/go-gitea/gitea/issues/21937))

🚀 Asciicast support ([#22448](https://github.com/go-gitea/gitea/issues/22448))

🚀 Cargo ([#21888](https://github.com/go-gitea/gitea/issues/21888)), Chef ([#22554](https://github.com/go-gitea/gitea/issues/22554)), Conda ([#22262](https://github.com/go-gitea/gitea/issues/22262)) package registries and package limits/cleanup ([#21584](https://github.com/go-gitea/gitea/issues/21584), [#21658](https://github.com/go-gitea/gitea/pull/21658))

🚀 Citing repos ([#19999](https://github.com/go-gitea/gitea/issues/19999))

🚀 Copy file content ([#21629](https://github.com/go-gitea/gitea/issues/21629))

🚀 Pre-built FreeBSD binaries ([#22397](https://github.com/go-gitea/gitea/issues/22397))

🚀 Highlight Note and Warning in markdown quotes ([#21711](https://github.com/go-gitea/gitea/issues/21711))

🚀 LFS GC ([#22385](https://github.com/go-gitea/gitea/issues/22385))

🚀 Projects for organizations/users ([#22235](https://github.com/go-gitea/gitea/issues/22235))

🚀 Referencing commits across repos ([#22645](https://github.com/go-gitea/gitea/issues/22645))

🚀 Reply by email ([#22056](https://github.com/go-gitea/gitea/issues/22056))

**Comment by Xosten** [comment]
Hi @kirkryan,

I have submitted a PR to update Gitea to 1.19.1. Keep an eye on PR #504 😉.

Cheers!
