### ISSUE TITLE
update Tailscale to 1.40.0

### ISSUE THREAD

**Issue by Celine1986** [getumbrel/umbrel-apps#517]
It seems that the current version in Umbrel isn't compatible with the iOS app version; Nostr Relay isn't working because of this.
I can only get a successful remote connection to my iPad with the newest version (when using the official ppa repo), but can't manually update Tailscale inside Umbrel to latest.

**Comment by nmfretz** [comment]
@Celine1986 Tailscale is now 1.40.1 on Umbrel! https://github.com/getumbrel/umbrel-apps/pull/525
