### ISSUE TITLE
Uptime Kuna upgrade to 1.21.3

### ISSUE THREAD

**Issue by alvarosamudio** [getumbrel/umbrel-apps#531]
Uptime kuna update released, bugs corrected

🐛 Bug Fixes
[Maintenance] Timezone issues that causes some maintenance do not start on time
[Maintenance] Same as Server Timezone cannot be saved
Upstream Dependencies
Update dependencies
Especially for Socket.io / engine.io ([GHSA-q9mw-68c2-j6m5](https://github.com/socketio/engine.io/security/advisories/GHSA-q9mw-68c2-j6m5))
🐻 Always perform a backup of your Uptime Kuma before upgrading.

[Uptime Kuna Version:1.21.3](https://github.com/louislam/uptime-kuma/releases/tag/1.21.3)

**Comment by nmfretz** [comment]
Sorry for forgetting to respond to this @alvarosamudio! Uptime Kuma is now updated to 1.23.0 FYI: https://github.com/getumbrel/umbrel-apps/pull/750
