### ISSUE TITLE
Placing a custom file into /etc

### ISSUE THREAD

**Issue by straylight-orbit** [getumbrel/umbrel-apps#539]
Our app requires a custom udev rules file to be placed into `/etc/udev/rules.d ` in order for a particular USB device to be detectable by the app.

How is this facilitated in Umbrel? Can a Docker image be configured to do this, or would such a file have to go into the system-level `/etc` directory?

**Comment by usernameisJim** [comment]
Closing duplicate issue: https://github.com/getumbrel/umbrel-apps/issues/592
