### ISSUE TITLE
Add Blockstream Liquid

### ISSUE THREAD

**Issue by Amiga500** [getumbrel/umbrel-apps#555]
Could it be a good idea to add Blockstream Liquid into Umbrel? And in case, suggest to install it, only if you have a rpi with 8GB of ram?

**Comment by nmfretz** [comment]
Elements Core (A Liquid network node) is available on the Umbrel App Store:  https://apps.umbrel.com/app/elements

If there is another implementation that people are hoping for please feel free to reopen this issue.
