### ISSUE TITLE
BTC RPC Explorer app - RPC terminal do not login

### ISSUE THREAD

**Issue by Darth-Coin** [getumbrel/umbrel-apps#569]
In BTC RPC app, when you try to enter in RPC Terminal tool it returns this erro
RPC Terminal / Browser require authentication. Set an authentication password via the 'BTCEXP_BASIC_AUTH_PASSWORD' environment variable (see .env-sample file for more info).

**Comment by arts3003** [comment]
What was the solution for this ?

**Comment by nmfretz** [comment]
I have just updated BTC RPC Explorer with RPC Terminal and RPC Browser functionality enabled: https://github.com/getumbrel/umbrel-apps/pull/1319
