### ISSUE TITLE
PhotoPrism WebDAV access

### ISSUE THREAD

**Issue by nevets963** [getumbrel/umbrel-apps#57]
Currently the App Proxy is protecting the WebDAV endpoints within PhotoPrism.

It appears safe to whitelist: `/originals` and `/import` as these are protected by HTTP Basic Auth by Photoprism.

More details here: https://docs.photoprism.app/user-guide/sync/webdav/#server-url

**Comment by tsnieman** [comment]
This Twitter thread contains conversation between PhotoPrism and PhotoSync developers about this issue: https://mobile.twitter.com/photosync_app/status/1542509638477680642
