### ISSUE TITLE
Pi-hole DHCP Fails

### ISSUE THREAD

**Issue by tkidd77** [getumbrel/umbrel-apps#574]
Running into this when enabling DHCP: https://github.com/pi-hole/docker-pi-hole/issues/814

**Comment by nmfretz** [comment]
Thanks for reporting this @tkidd7. 

For anyone making their way here, pi-hole on Umbrel [now runs in host network mode](https://github.com/getumbrel/umbrel-apps/pull/724), so setting up pi-hole as a DHCP server is now very simple.
