### ISSUE TITLE
Signing transactions with HWI bridge over Tor

### ISSUE THREAD

**Issue by jorge-lavin** [getumbrel/umbrel-apps#584]
When trying to sign a transaction using specter over Tor, a reuest is made to `http://127.0.0.1:/hwi` instead of the actual tor address, thus failing and displaying a `Failed to fetch` error.

Not sure if this is more a specter issue instead of a umbrel one.

**Comment by nmfretz** [comment]
Is anyone aware if this issue still persists in newer versions of Specter?

**Comment by nmfretz** [comment]
It looks like Specter now allows configuration of this url through their UI:

<img width="820" alt="image" src="https://github.com/getumbrel/umbrel-apps/assets/85373263/59f06339-66a7-421a-baa2-5aa9fe035760">

<img width="745" alt="image" src="https://github.com/getumbrel/umbrel-apps/assets/85373263/95f8299c-da39-4615-8543-499b5d2c0847">
