### ISSUE TITLE
Error: Vaultwarden requiring HTTPS

### ISSUE THREAD

**Issue by Berlelund** [getumbrel/umbrel-apps#585]
When trying to login on Vaultwarden over TOR the app prompts an error message "This browser requires HTTPS to use the web vault".

**Comment by nmfretz** [comment]
Thanks all for your input on this. Agreed that accessing the Vaultwarden UI via Tor is not ideal. We are stuck with this option right now, but we do plan to make this easier in the future as we update our OS. 

For now, I have added instructions to the app description to help people set up Vaultwarden: https://github.com/getumbrel/umbrel-apps/commit/426e11dd9140421739fdbf03c72e401fb66d26aa

<img width="917" alt="image" src="https://github.com/getumbrel/umbrel-apps/assets/85373263/172b0b6c-9304-49df-8277-95e7b0617d48">
