### ISSUE TITLE
Hundreds of DNS queries for mariadb.lan hitting outside DNS server

### ISSUE THREAD

**Issue by algotechio** [getumbrel/umbrel-apps#587]
On my network's pihole, I found thousands of DNS queries hitting the pihole DNS server:

![DNS queries](https://user-images.githubusercontent.com/49137998/159379666-f2c60371-0955-4c98-878e-83e40ee33a52.png)

The queries were coming from umbrel server.

The issue was that mariadb container was not started on the umbrel server.  Then the mariadb was not getting resolved by docker's DNS and instead forwarded the DNS resolution to the host.

I searched the code and it seems that the only place that uses docker host naming is this line (the other places seem to use direct IP addresses):

https://github.com/getumbrel/umbrel/blob/55d77495135ecfdd2060544ff3a7656822aba727/apps/mempool/docker-compose.yml#L25

**Comment by nmfretz** [comment]
Resolved by https://github.com/getumbrel/umbrel/commit/0724c398a8d244f4639bbbba87825e2209de03b5 in pre-1.0 umbrelOS, and no longer an issue in post 1.0 umbrelOS
