### ISSUE TITLE
LNBits webhook shows -1 after payment

### ISSUE THREAD

**Issue by mach5mach** [getumbrel/umbrel-apps#589]
I have LNBits on my umbrel.  I send a curl request to tor to create an invoice.  I pass in the webhook as http://[tor_address].onion:[tor_port]/invoicewebhook which is a tor hidden service on another computer.  After I make the payment, a red square with a -1 appears next to the webhook.

I checked the logs and I see that the payment was received but no evidence that the webhook POST command was ever sent.  Any help would be appreciated.  Any other documentation on how the webhook should be setup and what the json data returned would be helpful as well.

Here's the log after editing for personal info:
lnbits

web_1  | INFO:     10.21.21.49:56586 - "GET /api/v1/currencies HTTP/1.1" 200 OK
web_1  | INFO:     10.21.21.49:56590 - "GET /api/v1/wallet HTTP/1.1" 200 OK
web_1  | INFO:     10.21.21.49:56582 - "GET /api/v1/payments HTTP/1.1" 200 OK
web_1  | INFO:     10.21.21.49:56582 - "GET /api/v1/wallet HTTP/1.1" 200 OK
web_1  | INFO:     10.21.21.49:56578 - "GET /api/v1/payments/sse?api-key=XXXXXXXXXXXXXXXXX HTTP/1.1" 200 OK
web_1  | INFO:     10.21.21.49:53446 - "POST /api/v1/payments HTTP/1.1" 201 Created
web_1  | INFO:     10.21.21.49:53602 - "GET /wallet?usr=XXXXXXXXXXXXXXXXXXX&wal=XXXXXXXXXXXXXXXXXX HTTP/1.1" 200 OK
web_1  | INFO:     10.21.21.49:53602 - "GET /core/static/js/wallet.js HTTP/1.1" 304 Not Modified
web_1  | INFO:     10.21.21.49:53676 - "GET /static/bundle.js HTTP/1.1" 304 Not Modified
web_1  | INFO:     10.21.21.49:53678 - "GET /static/js/components.js HTTP/1.1" 304 Not Modified
web_1  | INFO:     10.21.21.49:53680 - "GET /static/js/base.js HTTP/1.1" 304 Not Modified
web_1  | adding sse listener <Queue maxsize=0>
web_1  | INFO:     10.21.21.49:53678 - "GET /api/v1/wallet HTTP/1.1" 200 OK
web_1  | INFO:     10.21.21.49:53602 - "GET /api/v1/currencies HTTP/1.1" 200 OK
web_1  | INFO:     10.21.21.49:53680 - "GET /api/v1/payments HTTP/1.1" 200 OK
web_1  | INFO:     10.21.21.49:53680 - "GET /api/v1/wallet HTTP/1.1" 200 OK
web_1  | INFO:     10.21.21.49:53676 - "GET /api/v1/payments/sse?api-key=XXXXXXXXXXXXXXXXXXXXXXXXX HTTP/1.1" 200 OK
web_1  | INFO:     10.21.21.49:58676 - "POST /api/v1/payments HTTP/1.1" 201 Created
web_1  | > got a payment notification XXXXXXXXXXXXXXXXXXXXXXXXXXxxx
web_1  | INFO:     10.21.21.49:59038 - "GET /wallet?usr=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&wal=XXXXXXXXXXXXXXXXXXXXXX HTTP/1.1" 200 OK
web_1  | INFO:     10.21.21.49:59038 - "GET /core/static/js/wallet.js HTTP/1.1" 304 Not Modified
web_1  | INFO:     10.21.21.49:59040 - "GET /static/bundle.js HTTP/1.1" 304 Not Modified
web_1  | INFO:     10.21.21.49:59042 - "GET /static/js/components.js HTTP/1.1" 304 Not Modified
web_1  | INFO:     10.21.21.49:59044 - "GET /static/js/base.js HTTP/1.1" 304 Not Modified
web_1  | adding sse listener <Queue maxsize=0>
web_1  | INFO:     10.21.21.49:59038 - "GET /api/v1/currencies HTTP/1.1" 200 OK
web_1  | INFO:     10.21.21.49:59042 - "GET /api/v1/wallet HTTP/1.1" 200 OK
web_1  | INFO:     10.21.21.49:59044 - "GET /api/v1/payments HTTP/1.1" 200 OK
web_1  | INFO:     10.21.21.49:59044 - "GET /api/v1/wallet HTTP/1.1" 200 OK
web_1  | INFO:     10.21.21.49:59040 - "GET /api/v1/payments/sse?api-key=XXXXXXXXXXXXXXXXXXXXXXX HTTP/1.1" 200 OK

**Comment by nmfretz** [comment]
Closing old issue. Thanks for opening an Issue directly in the LNBits repo mach5mach. Really appreciate it.
