### ISSUE TITLE
Electrs fails to upload data of deep wallets to sparrow wallet

### ISSUE THREAD

**Issue by Funman2** [getumbrel/umbrel-apps#611]
Hey, I have this issue of loading my wallet since 2 years with sparrow and electrs:

https://github.com/sparrowwallet/sparrow/issues/976#issue-1728476619

Would ask to integrate fulcrum  on umbrel, as a solution,that would be awesome!

**Comment by nmfretz** [comment]
Thanks for this request and sparrow details @Funman2. I have linked your request in this active Fulcrum request Issue to track it: https://github.com/getumbrel/umbrel-apps/issues/613

**Comment by Funman2** [comment]
Hi, thanks for your reply.  Actually the issue with Sparrow actually ceased to exist for me since I have moved from rasperry pi to umbrel home server last year. Now electrs works fast and reliable for me, so I have no urgent need for fulcrum, since it is not bitcoin only also....;-)

**Comment by nmfretz** [comment]
Thanks for the follow up @Funman2 🙏
