### ISSUE TITLE
[App Request] - Fulcrum

### ISSUE THREAD

**Issue by jimbrend** [getumbrel/umbrel-apps#613]
Many users in telegram and other channels have requested [Fulcrum](https://github.com/cculianu/Fulcrum), it is often touted as having faster capabilities than Electrs

Umbrel has had [this in the works ](https://github.com/search?q=org%3Agetumbrel%20fulcrum&type=code)

Didn't see it so reposting!

**Comment by IMPranshu** [comment]
I think it will be a issue of copyright unless someone has explicit permission from the dev
(C) 2019-2023 Calin Culianu [calin.culianu@gmail.com](mailto:calin.culianu@gmail.com)

**Comment by aphex3k** [comment]
Fulcrum does not provide a docker image themselves. While it should be not an issue to create a docker image running fulcrum, it should be hosted by the Fulcrum repository instead of a 3rd party. Once that step is completed, creating a Fulcrum app on docker, should not be an issue.

**Comment by nmfretz** [comment]
Noting another request for Fulcrum: https://github.com/getumbrel/umbrel-apps/issues/611

**Comment by Funman2** [comment]
Actually electrs performs well now for me on umbrel home, I used to have rasperry pi and there I had issues with Sparrow and loading wallets with many transactions. But since upgrade everything loads smooth in big wallets.

**Comment by nmfretz** [comment]
> Actually electrs performs well now for me on umbrel home, I used to have rasperry pi and there I had issues with Sparrow and loading wallets with many transactions. But since upgrade everything loads smooth in big wallets.

Nice, that's great to hear @Funman2. Thanks for following up 🙏

**Comment by nmfretz** [comment]
Noting this related Issue found by @aphex3k (https://github.com/getumbrel/umbrel-apps/issues/134), which having Fulcrum as the Electrum server instead of Electrs for Mempool would likely solve.
