### ISSUE TITLE
[Update Request] Invidious

### ISSUE THREAD

**Issue by mdrockwell** [getumbrel/umbrel-apps#632]
I’m seeing version `2023.06.11-a39abc9` on many public instances, but the latest version available through Umbrel is only `2023.04.10-961cae2`.

Thanks!

**Comment by nmfretz** [comment]
Thanks @mdrockwell, an update is coming very soon!

**Comment by nmfretz** [comment]
@mdrockwell update went live! https://github.com/getumbrel/umbrel-apps/pull/745
