### ISSUE TITLE
[Update Request] n8n - 15 releases behind

### ISSUE THREAD

**Issue by itsdoublearon** [getumbrel/umbrel-apps#635]
Can n8n please be updated. It's a few releases behind now.

Thanks

**Comment by Xosten** [comment]
> Can n8n please be updated. It's a few releases behind now.
> 
> Thanks

Hey @itsdoublearon, this will be fixed with #653 😉

**Comment by nmfretz** [comment]
Thanks @itsdoublearon. Closed by https://github.com/getumbrel/umbrel-apps/pull/653
