### ISSUE TITLE
App core-lightning crashes after Umbrel OS update from 0.5.3 to 0.5.4

### ISSUE THREAD

**Issue by klicha** [getumbrel/umbrel-apps#650]
The core-lightning app crashes repeatedly after a few minutes. It also causes backed lightningd to crash. It only takes core-lightning running in the browser window to crash.

When the core-lightning frontend is not running in the browser window, the lightningd backend works without problems.

The core-lightning-rtl application works without any problems.

Computer - Raspberry Pi 4 Model B Rev 1.1 4GB memory.

I am attaching the logs from the core-lightning_c-lightning-rest_1 and core-lightning_lightningd_1 container. Also troubleshooting debug log from Umbrel.

[core lightning error.txt](https://github.com/getumbrel/umbrel-apps/files/11881414/core.lightning.error.txt)
[umbrel-1687864229128-debug.log](https://github.com/getumbrel/umbrel-apps/files/11881417/umbrel-1687864229128-debug.log)

**Comment by nmfretz** [comment]
Closing old support issue. @klicha if you still encounter issues with Core-Lightning please reach out to our official support via our website https://umbrel.com/ or to the official Core Lightning discord: https://discord.com/invite/mE9s4rc5un
