### ISSUE TITLE
Application Request: Overleaf

### ISSUE THREAD

**Issue by howardheaton** [getumbrel/umbrel-apps#668]
It'd be awesome to be able to self-host technical LaTex docs via Umbrel. 

Overleaf is a widely used tool for writing with LaTex; I'd greatly appreciate any help getting this added to Umbrel's app store.

Repo: https://github.com/overleaf/overleaf

**Comment by IMPranshu** [comment]
Hey @howardheaton there is currently no support for `arm` devices for this app. I will anyways try to make a docker image for arm devices.

**Comment by howardheaton** [comment]
Hey Pranshu, just following up, thanks a ton for looking into this. I didn't realize there isn't arm support. Was there any success here?

I'm not versed in things like docker, but I'd be happy to learn how to maintain updates (so that, per #687,  I could hopefully help reduce the team's burden of keeping this app up-to-date in the umbrel store).

**Comment by howardheaton** [comment]
Oh, it looks like this has been brought up by others and the request for `arm` support has essentially been shut down for Overleaf. Let's drop Overleaf from consideration as an Umbrel app; I will find an alternative.
