### ISSUE TITLE
app store schema question/suggestion

### ISSUE THREAD

**Issue by th3fallen** [getumbrel/umbrel-apps#67]
Why not drop the .yml file requirement for apps and pull all the data directly from docker hub via their compose file they're providing. versioning is already handled there anyway.

**Comment by nevets963** [comment]
@th3fallen If you're referring `docker-compose.yml` then what @kroese has said is true here. If you mean `umbrel-app.yml`, this is a basic app manifest file so that Umbrel knows data like the app name, author, support email address, etc that we display within the frontend of Umbrel.
