### ISSUE TITLE
CORS and Auth app for external or non docker application

### ISSUE THREAD

**Issue by brunoAmado** [getumbrel/umbrel-apps#69]
I'm creating a prove of concept that use some aplication in my Umbrel node (raspberry4)
but with the new version I have some problem auth via fetch but want to use the umbrel proxy_auth.

I don't want to use the inbuilt API token system but the Umbrel proxy one seams a good bet to ease the CORS problem I have with some applications.

did someone already use fetch or axios with crediencial from external application.
(i.e use my APi to access an other API like btc-rpc-explorer with CORDS )

**Comment by lukechilds** [comment]
To confirm your use case is that you are building a web app that you want to be able to interface with the btc-rpc-explorer API running on your but it doesn't work due to CORS errors, is that correct?

Could you explain your use case in a little more detail?

**Comment by lukechilds** [comment]
From what I can see the btc-rpc-explorer app doesn't return a CORS header so this is the expected behaviour.

<img width="1176" alt="Screenshot 2022-07-11 at 19 16 31" src="https://user-images.githubusercontent.com/2123375/178263084-c963393b-1bc1-42c9-a112-8f4f44741496.png">

**Comment by brunoAmado** [comment]
Yes, you right @lukechilds  , but being that way, I was expecting, maybe wrongly, that app_proxy was an authorized proxy, can do the fetch call then use a CORS from the proxy. [https://github.com/janoside/btc-rpc-explorer/issues/451](url)

res.setHeader("Access-Control-Allow-Origin", "*");

No need for me to create an addictional proxy :)
But I don't know how to use the app_proxy without disabling in docker_composite [https://github.com/getumbrel/umbrel-apps#advanced-configuration](url)
PROXY_AUTH_ADD: "false"

**Comment by lukechilds** [comment]
I ah see.

>I was expecting, maybe wrongly, that app_proxy was an authorized proxy, can do the fetch call then use a CORS from the proxy. [https://github.com/janoside/btc-rpc-explorer/issues/451](https://github.com/getumbrel/umbrel-apps/issues/url)

That's correct, the Umbrel app proxy is authenticated. This stops unauthenticated users from accessing your apps if they can ping the port.

However CORS is used to rpevent a different attack. It prevents malicious websites from accessing authenticated resources on behalf of the user. If the Umbrel app proxy injected the CORS header into all apps, this would create a significant vulnerability where secure apps would now become insecure and vulnerable to CSRF attacks.

Whether an app wants to add CORS headers or not heavily relates to what that app does and how it functions. It should be the apps responsibility to add CORS headers to responses that are safe to be accessed cross origin and not add CORS headers to responses that aren't. This isn't really something that Umbrel should be doing on it's own.

**Comment by lukechilds** [comment]
>No need for me to create an addictional proxy :)

I would suggest opening an issue on the BTC RPC Explorer project and asking them to add the CORS header to API responses that are safe to be accessed across origins. Note that this would now mean any website is able to make requests the BTC RPC Explorer instance on your Umbrel. They may not think this is a good idea to have enabled for most users. Potentially it could be disabled by default and enabled by a setting for users that want it.

>But I don't know how to use the app_proxy without disabling in docker_composite [https://github.com/getumbrel/umbrel-apps#advanced-configuration](https://github.com/getumbrel/umbrel-apps/issues/url)
PROXY_AUTH_ADD: "false"

You can also use:

```yaml
PROXY_AUTH_WHITELIST: "/api/*"
```

To bypass auth proxy for API routes but not the UI routes if that is useful. I have not looked into how BTC RPC Explorer works to check if this is safe to do.

**Comment by nmfretz** [comment]
Closing this issue as resolved by Luke's suggestions here: https://github.com/getumbrel/umbrel-apps/issues/69#issuecomment-1181384950

@brunoAmado please reopen this if you are still needing help.
