### ISSUE TITLE
Update `Invidious` to latest version to fix broken videos

### ISSUE THREAD

**Issue by anthony-robin** [getumbrel/umbrel-apps#737]
Youtube seems to make some update on its backend which make Invidious unusable on Umbrel for a while.

Indeed, all videos end up with the error `The media could not be loaded, either because the server or network failed or because the format is not supported.`

Issue has been reported and fixed on Invidious repository at https://github.com/iv-org/invidious/pull/4037.

Umbrel should update the current app version to the last one that include the fix.

Other instances that are more up-to-date works great for videos that crash on Umbrel. For example, https://inv.makerlab.tech is at `Current version: 2023.08.07-3450896 @ master`.

Thank you :)

**Comment by ceramicwhite** [comment]
@nmfretz Done: https://github.com/getumbrel/umbrel-apps/pull/745

**Comment by nmfretz** [comment]
Thanks @ceramicwhite! The update is now live https://github.com/getumbrel/umbrel-apps/pull/745
