### ISSUE TITLE
Update `Whoogle` to latest version

### ISSUE THREAD

**Issue by anthony-robin** [getumbrel/umbrel-apps#738]
Whoogle app is broken since few days as explained in the issue: https://github.com/benbusby/whoogle-search/issues/1053

The new `v0.8.3` version has just been released and fix the issue.

Thank you :)

**Comment by nmfretz** [comment]
Thanks for letting us know @anthony-robin! Looks like it was affecting all EU users. The new update https://github.com/getumbrel/umbrel-apps/pull/740  is live in the app store.

**Comment by anthony-robin** [comment]
@nmfretz Thank you for fixing it so quickly !
