### ISSUE TITLE
Homebridge - Deprecated Image

### ISSUE THREAD

**Issue by Xosten** [getumbrel/umbrel-apps#755]
Hi,

I'd like to bring to your attention that the current image being used for homebridge, `oznu/homebridge`, is no longer being maintained. The official repository strongly recommends transitioning to the new image, which you can learn more about [here](https://github.com/homebridge/docker-homebridge#important-update).

However, there's a concern with the newly maintained image. They have opted not to utilize versioned docker image tags, instead only offering a `latest` and an `ubuntu` tag. This isn't ideal given our current configuration in the `docker-compose.yml` file. To address this, I'm considering a potential solution: utilizing the SHA fingerprint of the `latest` docker image and tying the `umbrel-app.yml` version to the upstream GitHub [repository](https://github.com/homebridge/homebridge) version.

I'm opening this issue to discuss about this as we're using a non-maintained docker image, looking at the official repo. 

@nmfretz, if you have a moment to share your thoughts on this topic, it would be greatly appreciated 😃

**Comment by nmfretz** [comment]
Hey @Xosten thanks for keeping on top of this, great work! 

I agree with your suggested approach. We actually do something similar for [Chatbot UI](https://github.com/getumbrel/umbrel-apps/blob/master/chatbot-ui/docker-compose.yml), where we version with the date and then include the commit in the umbrel-app.yml release notes: https://github.com/getumbrel/umbrel-apps/blob/acc169fc17a6b740adc6296138c7e97f3412c20b/chatbot-ui/umbrel-app.yml#L54

**Comment by Xosten** [comment]
Hey @nmfretz, thanks for taking the time to look into this. 

I will do the same as what you did for Chatbot UI in this case. 

Please leave the issue open while I work on the PR 😉

Cheers!

**Comment by nmfretz** [comment]
Sounds good! And please feel free to try something different if you think of a better approach than what we have done for Chatbot.

**Comment by nmfretz** [comment]
Closed by https://github.com/getumbrel/umbrel-apps/commit/ae83cf52965b4607576cf87d180b2dc6d6c29b31.

Official package now includes version tags: https://github.com/homebridge/docker-homebridge/pkgs/container/homebridge
