### ISSUE TITLE
Update LNbits to 0.11.1

### ISSUE THREAD

**Issue by ElucGeek** [getumbrel/umbrel-apps#821]
Hello
Is it possible to update LNbits which has a currently a 2 months old version with 2 new in between.
By the way can I manually update it without waiting on Umbrel to push the update?

**Comment by nmfretz** [comment]
Thanks @ElucGeek, we've now updated to 0.11.1 https://github.com/getumbrel/umbrel-apps/pull/822

**Comment by nmfretz** [comment]
>By the way can I manually update it without waiting on Umbrel to push the update?

I don't recommend doing this, but here's how you can: 
Edit the docker-compose.yml of your lnbits install with your desired lnbitsdocker/lnbits-legend image. This file would be found in the `~/umbrel/app-data/lnbits` directory. You could then run `sudo ~umbrel/scripts/app restart lnbits`.

Alternatively, you could open a PR here with the new lnbitsdocker/lnbits-legend to help speed things along!

**Comment by ElucGeek** [comment]
Amazing, thanks for the updates and the details.
