### ISSUE TITLE
Nextcloud 25.0.13

### ISSUE THREAD

**Issue by MyUmbrel** [getumbrel/umbrel-apps#863]
Can someone please update Nextcloud to 25.0.13

**Comment by murniox** [comment]
Better directly to Nextcloud 27.
Is there a reason why we are so far behind?

**Comment by nmfretz** [comment]
Closed by https://github.com/getumbrel/umbrel-apps/commit/89c3bdb9a97f3fc227c52aa67e50ebcd03f3ea96
