### ISSUE TITLE
Update LNbits to 0.11.2

### ISSUE THREAD

**Issue by aki-mizu** [getumbrel/umbrel-apps#899]
0.11.2 was released two weeks ago with many feature added including using Alby wallet as funding source, any timeline when this update will be available within umbrel? Thanks!

**Comment by smolgrrr** [comment]
I'll take a look at this now, thanks!

**Comment by smolgrrr** [comment]
Unfortunately, this may be a little difficult to configure, and would likely require users to add their getalby details to the docker-compose.yml file themself, however I will double-check.
