### ISSUE TITLE
Thunderhub 0.13.29 logouts immediatelly

### ISSUE THREAD

**Issue by jviki** [getumbrel/umbrel-apps#920]
I have just updated to the newest Thunderhub. I can log in, however, almost immediately, it logs me out. Thus, the application becomes unusable.

umbrelOS Version: 0.5.4

**Comment by nmfretz** [comment]
Hi @jviki, I am unable to reproduce. If you are still having issues with Thunderhub please reach out to us on our official support channel through our website https://umbrel.com/, or to the Thunderhub app developer https://github.com/apotdevin/thunderhub/issues
