### ISSUE TITLE
Umbrel proxy and websocket

### ISSUE THREAD

**Issue by Impa10r** [getumbrel/umbrel-apps#931]
Hello. I built an app that uses Websocket to update certain information on its page. It works great, including in Docker, but fails to run on Umbrel. Is there something I can do to fix it? The listener is in Go using "github.com/gorilla/websocket". 

Could someone explain what these parameters do in docker-compose.yml:
services:
  app_proxy:
    environment:
      APP_HOST:

and

networks:
      default:
        ipv4_address:

Thanks!!!

**Comment by maipal-c** [comment]
hey @Impa10r, service app_proxy is an container that have an simple express app running init with http-proxy-middleware and it act as an gateway of authentication.

for more detailed info you can shell into it and checkout files "bin/www" its actually an index.js file renamed to www and in package.json this is the file running as an entrypoint and inside this it will look for APP_HOST and APP_PORT variable and proxy the req to these variables. 

this container contain some simple js code that you easily understand or maybe use gpt or gemini or explain better

**Comment by Impa10r** [comment]
thanks for the reply. I found a work around to not use ws in my application. closing the issue.
