### ISSUE TITLE
App Request AdGuard Home

### ISSUE THREAD

**Issue by lxndrblz** [getumbrel/umbrel-apps#939]
Hi there,

I'd like to request an alternative to PiHole called Adguard Home, which from my own experience runs a bit more reliable and has a more intuitive user interface.

It already comes as a Docker application and should be fairly easy to port:
https://github.com/AdguardTeam/AdGuardHome

**Comment by nmfretz** [comment]
Adguard Home is now available in the app store!

Closed by https://github.com/getumbrel/umbrel-apps/commit/098c868b3f2ace8f9fa0db1e2c0efa6dc28c145f
