### ISSUE TITLE
public pool - no update in blockheight/ work template

### ISSUE THREAD

**Issue by GarmadonGamer** [getumbrel/umbrel-apps#946]
Great news to now be able to run a solopool on umbrel! but i seem to encounter a problem. As the pool runs the blockheight does not change. Bitcoinnode goes up butt public-pool stays at the blockheigt it started. Where does the worktemplate come from? Looks like the miner run on old work
![image](https://github.com/getumbrel/umbrel-apps/assets/157493864/ec64a6a7-7820-4f3a-a666-df4ed67febbc)
![image](https://github.com/getumbrel/umbrel-apps/assets/157493864/1f472fb8-9f73-4c87-920e-bb727b1e01f3)

_Originally posted by @GarmadonGamer in https://github.com/getumbrel/umbrel-apps/issues/915#issuecomment-1906023347_

**Comment by smolgrrr** [comment]
investigating this now

**Comment by smolgrrr** [comment]
this should be resolved now https://github.com/getumbrel/umbrel-apps/pull/947
