### ISSUE TITLE
btcpay + https

### ISSUE THREAD

**Issue by jaonoctus** [getumbrel/umbrel-apps#95]
How do I enable HTTPS certs for a domain on btcpay (Umbrel v0.5.1)?

**Comment by nevets963** [comment]
@jaonoctus We currently don't support this out of the box. But a few people have written tutorials on how you can do this yourself. Here is one example: https://github.com/getumbrel/umbrel/issues/1428#issue-1265592593 from @Jorijn

**Comment by jaonoctus** [comment]
I'll take a look, thank you @nevets963

Closing this issue for now
