### ISSUE TITLE
FreshRSS /api/* should not be behind proxy

### ISSUE THREAD

**Issue by josewal** [getumbrel/umbrel-apps#969]
I wanted to connect my FreshRSS to NetNewsWire but for that /api/* cannot be behind proxy.

**Comment by nmfretz** [comment]
Thanks for letting us know @josewal! We will push an update.

**Comment by nmfretz** [comment]
Thanks again for this @josewal. FreshRSS is now updated: https://github.com/getumbrel/umbrel-apps/pull/975

I tested the flow for connecting NetNewsWire to FreshRSS on Umbrel and it works well. Enjoy!
