### ISSUE TITLE
Application request: Plex Media Server

### ISSUE THREAD

**Issue by johnpc** [getumbrel/umbrel-apps#97]
Would be awesome if Plex was available as an umbrel app. This is their docker image: https://github.com/plexinc/pms-docker

**Comment by aphex3k** [comment]
PMS is now available in the app store: https://github.com/getumbrel/umbrel-apps/tree/master/plex

**Comment by thashm** [comment]
No casting devices can be found on umbrel, yet on windows plesk media server casting devices like chromecast TV, etc can be found. How to fix this?
