### ISSUE TITLE
[App Request] — Technitium DNS Server

### ISSUE THREAD

**Issue by wont-stream** [getumbrel/umbrel-apps#991]
Would be nice to have something a little more professional than Pi-hole

**Comment by highghlow** [comment]
I have started working on this

**Comment by highghlow** [comment]
Here you go

**Comment by nmfretz** [comment]
Technitium DNS is now available in the app store thanks to the work of @highghlow! Closed by https://github.com/getumbrel/umbrel-apps/commit/d7b4e80fc905c3f9ac2f5914c5b877e26e550950

**Comment by wont-stream** [comment]
Thank you ❤️
