### ISSUE TITLE
[App Request] — memos

### ISSUE THREAD

**Issue by wont-stream** [getumbrel/umbrel-apps#992]
A good piece of note taking software would be a nice addition to umbrel

https://github.com/usememos/memos

**Comment by marciasmedia** [comment]
I already have it and use it :)

![obraz](https://github.com/getumbrel/umbrel-apps/assets/166677805/1a2c0ab7-4886-4f4a-8627-e072f51133dc)

![obraz](https://github.com/getumbrel/umbrel-apps/assets/166677805/488dfc04-a628-4929-8a9c-bbe943094de4)


![obraz](https://github.com/getumbrel/umbrel-apps/assets/166677805/7847e17a-3187-4781-b2e8-2f8de2527dd6)

**Comment by FlyinPancake** [comment]
can you close the issue? :heart:

**Comment by wont-stream** [comment]
Thank you so much!
